# Problem statement
#### With your high school reunion fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on a Monday. Given these daily weights, build an array with your average weight per weekend. 

In [2]:
import numpy as np
                    # linspace array        +       # random noise array                 
weights =  np.round(np.linspace(185.0, 178.5, 35) + np.random.uniform(-0.5, 0.5, 35),1)
weights = weights.reshape(5,7) # to make it 5 rows(5 weeks) and 7 columns(7 weekdays) , we just reshape it , so we can index easily
weights

array([[185.3, 184.4, 184.1, 184.8, 184.5, 183.6, 183.4],
       [183.8, 183.2, 182.8, 182.8, 183.1, 183.1, 182.4],
       [182.8, 181.7, 182.1, 181.9, 181.7, 181.3, 181.6],
       [181.5, 180.6, 180.6, 180.3, 180.7, 179.6, 180.2],
       [180. , 179.2, 179. , 179.5, 178.6, 179.1, 178.9]])

What is `numpy.linspace()`?
numpy.linspace(start, stop, num) generates evenly spaced numbers over a specified range.

```python
np.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)
```
1. `start` → The starting value of the sequence.
2. `stop` → The ending value of the sequence.
3. `num` → The number of samples to generate (default: 50).
4. `endpoint=True` → Includes the stop value in the sequence. If False, the sequence stops before stop.Default:True
5. `retstep=False` → If True, it returns the step size between numbers.
6. `dtype=None` → Specifies the data type (optional).


In [11]:
# Example 1: Generating 5 evenly spaced numbers
print(np.linspace(1,10,5,dtype=int))
# 💡 Explanation: The range 1 → 10 is divided into 5 equal intervals. (Math : 10/5(num) = 2; from 1 , add 2 to each output element until 10(inclusive))
arr_and_step = np.linspace(1, 10, 5,dtype=int, retstep=True) 
# 💡 Explanation: The difference between consecutive elements is 2.25
arr_and_step


[ 1  3  5  7 10]


(array([ 1,  3,  5,  7, 10]), np.float64(2.25))

### Conclusion
-  linspace() is best when you want a specific number of values (e.g., exactly 35 weights).
- arange() is better when using a fixed step size (e.g., every 0.5 units).

## Continue from problem statement solution

In [4]:
# resultant array , 
# So each week starts on Monday, so weekends are at index positions [5, 6], [12, 13], [19, 20], [26, 27], and [33, 34].
avg_weight_for_each_weekend = np.zeros((5))
avg_weight_for_each_weekend[:] =  np.mean(weights[:,5:7], axis=1)
avg_weight_for_each_weekend # So here we find the average weight for each weekend

array([183.5 , 182.75, 181.45, 179.9 , 179.  ])

## But how axis = 1 works?

#### 🧩 Understanding NumPy Axes
So Every NumPy array has dimensions we already know, and each dimension has an axis:

- 1D array (shape = (n,)) → Only one axis: axis=0
- 2D array (shape = (m, n)) → Two axes:
   - axis=0 → Operates column-wise (vertical direction)
   - axis=1 → Operates row-wise (horizontal direction)
- 3D array (shape = (p, m, n)) → Three axes:
    - axis=0 → Across depth (layers)
    - axis=1 → Across rows
    - axis=2 → Across columns

...,so on for n number of dimensions...

Let's say you have this 2D array:


In [5]:
arr = np.array([
    [1, 2, 3],   # Row 0
    [4, 5, 6],   # Row 1
    [7, 8, 9]    # Row 2
])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 1️⃣ np.mean(arr, axis=0) → Column-wise (Downward)

```python
arr =  [[ 1   2   3 ]  
        [ 4   5   6 ]  
        [ 7   8   9 ]]

```

Computes mean of each column:
- (1 + 4 + 7) / 3 = 4.0
- (2 + 5 + 8) / 3 = 5.0
- (3 + 6 + 9) / 3 = 6.0

***See 👇🏻***

In [6]:
np.mean(arr, axis=0)  
# Output: [4.0 5.0 6.0]  (shape = (3,))

array([4., 5., 6.])

#### 2️⃣ np.mean(arr, axis=1) → Row-wise (Sideways) 

```python
arr =  [[ 1   2   3 ]  
        [ 4   5   6 ]  
        [ 7   8   9 ]]

```


Computes mean of each row(**That' what we did to find solution for our exercise , because what we need **):
- (1 + 2 + 3) / 3 = 2.0
- (4 + 5 + 6) / 3 = 5.0
- (7 + 8 + 9) / 3 = 8.0

***See 👇🏻***

In [7]:
np.mean(arr, axis=1)  

array([2., 5., 8.])

#### But this  np.mean(arr) , gives us mean of all elements in array , in result we get single value as output 

In [8]:
# 1+2+3+4+5+6+7+8+9 = 45
# 45/9 = 5
np.mean(arr)

np.float64(5.0)

#### 🛠 Applying This to our Case (weights[:,5:7])
***this gives us array of 👇🏻***

In [9]:

weekend_weights = weights[:, 5:7]
weekend_weights # of 2 dimension

array([[183.6, 183.4],
       [183.1, 182.4],
       [181.3, 181.6],
       [179.6, 180.2],
       [179.1, 178.9]])

With axis=1
```python
np.mean(weights[:,5:7], axis=1)
```

- `weights[:, 5:7]` selects two columns (Sat & Sun) → (5,2) shape.
- `axis=1` → Computes mean across each row (each week's Sat & Sun).
- Output shape: `(5,)` → One mean per week.

In [10]:
# So basically it calaculates the mean of a matrix , but row-wise(Horizontal wise) as axis param is 1
np.mean(weights[:,5:7], axis=1) # and each element of this array assign to corresponding element of `avg_weight_for_each_weekend` array

array([183.5 , 182.75, 181.45, 179.9 , 179.  ])

[Btw we have one more solution of this exercise from `GormAnalysis`](https://youtu.be/eClQWW_gbFk?si=5ZJ7n7rUB0deOECz&t=1947)