# Numpy is a fundamental library for scientific computing in Python. It provides a powerful and efficient way to work with arrays and matrices in Python.

## Advantages of using numpy arrays over python lists :

### 1. Numpy arrays are faster than python lists.
### 2. Numpy arrays are more memory efficient than python lists, as they consume less memory.

## Basic difference between arrays and lists :
###  List : Comma separated values , Numpy array : Non-comma separated values 


## numpy provides enormous amount of math functions that operate on these arrays or matrices.


## importance of numpy  : 
### math logical , shape manipulation , sorting , I/O discrete fourier transforms, basic linear algebra , basic statistics operations,random simulation and much more . 




In [121]:
import numpy as np
print(type(np.array([1, 2, 3])))# <class 'numpy.ndarray'> --> means some n-dimentional array
# numpy arrays must contain same type and dimension of data 
# to check type of data in numpy array
print(np.array([1, 2, '3',True]).dtype) , # numpy infere all types as string as when we have string in numpy array , it turns every element into string

<class 'numpy.ndarray'>
<U11


(None,)

In [ ]:
# Basic matrix 

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
# check dimension 
print(matrix.shape) # means 3 rows and 3 columns ,but note : this is a 2d array as 1 block depth(array and vectors are not same in numpy)
# arrays dimension are define by number of brackets
print(matrix.ndim) # means 2d array  , for check array dimension

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


#### list vs numpy array speed comparision


In [3]:
%timeit [_ for _ in range(1000)]

21.8 µs ± 1.45 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:

import numpy as np
%timeit np.arange(1000)*2 # np.arange is used to create an array with range of numbers , here 0-999  and then we scale it by 2 , basically create 1000 dimensional vector , but note : this is a 1d array

2.11 µs ± 38.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
%timeit np.array([_ for _ in range(1000)])*2 # its very silly thing to do why, just see the time comparison

59.3 µs ± 1.34 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Why this happened even (np.arange takes very less time than above code , although we are creating an numpy array in both cases)
#### The key difference between the two operations lies in how the arrays are created:
- 1️⃣ `np.arange(1000)` creates a NumPy array efficiently in C without using Python loops.As python loops are obviously very slow.
- Multiplication is applied directly on the NumPy array, utilizing vectorized operations optimized with low-level C implementations.

- 2️⃣ `np.array([_ for _ in range(1000)]) * 2`
- [ _ for _ in range(1000) ] first creates a Python list using list comprehension.
- np.array(...) then converts the list into a NumPy array, which adds overhead.
- Multiplication is then performed, but the overhead of list creation + conversion makes this approach significantly slower.

##### So Why is np.arange(1000) faster?
- Avoids Python loops: np.arange(1000) is implemented in C, making it much faster than list comprehension.
- No intermediate list creation: np.array([_ for _ in range(1000)]) first creates a Python list in memory, then converts it to a NumPy array, which is an extra step.
- Memory efficiency: np.arange(1000) directly creates an array with efficient memory layout, while the list-comprehension method involves unnecessary memory allocation.



In [ ]:
a= np.array([[1,2,4] ,[2,3,4]])


(2, 3)


In [ ]:
# code to create matrix with user input
row = int(input("Enter row number: "))

col = int(input("Enter col number: "))

input_Matrix = np.zeros((row, col)) # np.zeros is used to create a matrix of zeros , with specified rows and columns , by default it takes rows 0 , if only 1 number is given 


for i in range(row):
    for j in range(col):
        input_Matrix[i][j] = int(input(f"Enter value for {i+1} row and {j+1} column: "))

print(input_Matrix)

[[1. 0.]
 [0. 1.]]


In [ ]:
print(np.full((7,7),2)) # np.full is used to create a matrix of specified size with specified value , 1st parameter is size and 2nd parameter is value
print(np.full(2,2)) 

print(np.size(np.full(2,2))) # to check how many elements are there in the array

[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]
[2 2]
2
