# Numpy is a fundamental library for scientific computing in Python. It provides a powerful and efficient way to work with arrays and matrices in Python.

## Advantages of using numpy arrays over python lists :

### 1. Numpy arrays are faster than python lists.
### 2. Numpy arrays are more memory efficient than python lists, as they consume less memory.

## Basic difference between arrays and lists :
###  List : Comma separated values , Numpy array : Non-comma separated values 


## numpy provides enormous amount of math functions that operate on these arrays or matrices.


## importance of numpy  : 
### math logical , shape manipulation , sorting , I/O discrete fourier transforms, basic linear algebra , basic statistics operations,random simulation and much more . 




In [42]:
import numpy as np
print(type(np.array([1, 2, 3])))# <class 'numpy.ndarray'> --> means some n-dimentional array

<class 'numpy.ndarray'>


In [43]:
# Basic matrix 

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### list vs numpy array speed comparision


In [44]:
%timeit [_ for _ in range(1000)]

19.6 µs ± 924 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [45]:

import timeit



import numpy as np
%timeit np.arange(1000)*2 # np.arange is used to create an array with range of numbers , here 0-999  and then we scale it by 2

4.36 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [46]:
%timeit np.array([_ for _ in range(1000)])*2 # its very silly thing to do why, just see the time comparison

119 µs ± 6.87 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Why this happened even (np.arange takes very less time than above code , although we are creating an numpy array in both cases)
#### The key difference between the two operations lies in how the arrays are created:
- 1️⃣ `np.arange(1000)` creates a NumPy array efficiently in C without using Python loops.As python loops are obviously very slow.
- Multiplication is applied directly on the NumPy array, utilizing vectorized operations optimized with low-level C implementations.

- 2️⃣ `np.array([_ for _ in range(1000)]) * 2`
- [ _ for _ in range(1000) ] first creates a Python list using list comprehension.
- np.array(...) then converts the list into a NumPy array, which adds overhead.
- Multiplication is then performed, but the overhead of list creation + conversion makes this approach significantly slower.

##### So Why is np.arange(1000) faster?
- Avoids Python loops: np.arange(1000) is implemented in C, making it much faster than list comprehension.
- No intermediate list creation: np.array([_ for _ in range(1000)]) first creates a Python list in memory, then converts it to a NumPy array, which is an extra step.
- Memory efficiency: np.arange(1000) directly creates an array with efficient memory layout, while the list-comprehension method involves unnecessary memory allocation.

