# Problem statement

#### After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner. You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

## Setup
**[Full setup explanation by `GormAnalysis`](https://youtu.be/eClQWW_gbFk?si=tDaU-5Bi2aQ9ctDH&t=2041)**

In [2]:
import numpy as np 
rng = np.random.default_rng(77)
gold = rng.integers(low=0, high=10, size=(7, 7)) 
print(gold)


[[0 7 6 5 7 2 8]
 [3 9 3 3 3 3 8]
 [1 0 9 3 2 7 7]
 [7 7 6 9 1 7 3]
 [6 8 4 9 2 7 1]
 [1 0 8 1 1 4 3]
 [2 3 3 3 6 1 5]]


In [3]:
locs = np.array([[0, 4], [2, 2], [2, 3], [5,1], [6,3]])
print(locs)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


In [4]:
goldDiscoveredAtEachLoc = np.zeros(5) 
goldDiscoveredAtEachLoc

array([0., 0., 0., 0., 0.])

In [6]:
#                              This row    This column
goldDiscoveredAtEachLoc = gold[locs[:, 0], locs[:, 1]]
goldDiscoveredAtEachLoc
for i,v in enumerate(goldDiscoveredAtEachLoc):
    print(f'Gold discovered at row {locs[i][0]} and column {locs[i][1]} is {v} Unit')

Gold discovered at row 0 and column 4 is 7 Unit
Gold discovered at row 2 and column 2 is 9 Unit
Gold discovered at row 2 and column 3 is 3 Unit
Gold discovered at row 5 and column 1 is 0 Unit
Gold discovered at row 6 and column 3 is 3 Unit
