# Problem Statement
#### You decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken restaurant, Chic-fil-A. You buy three billboards evenly spaced starting on mile marker 17 and ending on mile marker 28. Then you buy another three billboards evenly spaced starting on mile marker 32 and ending on mile marker 36. In order, from mile marker 17 to 36, your billboards display these ads: A, B, C, C, B, A. Determine how far each "C" ad is from your restaurant which is located at mile marker 30.

In [1]:
# 1st solution

import numpy as np
first_three_billboards =np.linspace(17, 28, 3,dtype=int)
second_three_billboards=np.linspace(32, 36, 3,dtype=int)

print(first_three_billboards)
print(second_three_billboards)
resturantLocation = 30

# abs -> absolute value from 0, here to ensure the distance is positive
distances_from_restaurant = np.array([abs(resturantLocation - first_three_billboards[-1]), abs(second_three_billboards[-1] - resturantLocation)])
print(distances_from_restaurant) 


# ------------------------------------------------------------ Not required in the question ------------------------------------------------------------
distances_from_restaurant.sum() / 2 # average distance from both "C" billboards, btw this is not ask in the question


[17 22 28]
[32 34 36]
[2 6]


4.0

In [2]:
# 2nd Solution
# ----- So we can also pass array value to start and stop parameter in np.linspace() method, we gonna leverage this to optimize 1st solution

# Means stop value for 17 is 28 and stop value for 32 is 36
all_billboards = np.linspace(start=[17,32], stop=[28,36], num=3 ,dtype=int)
print(all_billboards)
distances_from_restaurant = np.abs(all_billboards[-1] - resturantLocation)  
distances_from_restaurant

[[17 32]
 [22 34]
 [28 36]]


array([2, 6])

## We also have axis param in np.linspace method

In [5]:
# Same like np.mean axis param, axis 0 for column wise, axis 1 for row wise ...
example = np.linspace(start=[17,32,1], stop=[28,36,10], num=3 ,dtype=int,axis=1)
print(example)


[[17 22 28]
 [32 34 36]
 [ 1  5 10]]
