# Problem statement
#### With your high school reunion fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on a Monday. Given these daily weights, build an array with your average weight per weekend. 

In [ ]:
import numpy as np
                    # linspace array        +       # random noise array                 
weights =  np.round(np.linspace(185.0, 178.5, 35) + np.random.uniform(-0.5, 0.5, 35),1)
weights = weights.reshape(5,7) # to make it 5 rows(5 weeks) and 7 columns(7 weekdays) , we just reshape it , so we can index easily
weights

array([[185.4, 184.6, 185.1, 184.9, 184.3, 184.2, 183.4],
       [184.1, 183.1, 183.6, 182.8, 183.3, 182.4, 182.9],
       [182. , 182.5, 182.2, 181.4, 181.2, 181.4, 181. ],
       [181.5, 181.2, 180.5, 180.1, 180.4, 180. , 179.8],
       [180. , 179.7, 179.7, 179.5, 179.1, 179. , 178.7]])

What is `numpy.linspace()`?
numpy.linspace(start, stop, num) generates evenly spaced numbers over a specified range.

```python
np.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)
```
1. `start` → The starting value of the sequence.
2. `stop` → The ending value of the sequence.
3. `num` → The number of samples to generate (default: 50).
4. `endpoint=True` → Includes the stop value in the sequence. If False, the sequence stops before stop.
5. `retstep=False` → If True, it returns the step size between numbers.
6. `dtype=None` → Specifies the data type (optional).


In [40]:
# Example 1: Generating 5 evenly spaced numbers
print(np.linspace(1,10,5,dtype=int))
# 💡 Explanation: The range 1 → 10 is divided into 5 equal intervals. (Math : 10/5(num) = 2; from 1 , add 2 to each output element until 10(inclusive))
arr_and_step = np.linspace(1, 10, 5,dtype=int, retstep=True) 
# 💡 Explanation: The difference between consecutive elements is 2.25
arr_and_step



[ 1  3  5  7 10]


(array([ 1,  3,  5,  7, 10]), 2.25)

### Conclusion
-  linspace() is best when you want a specific number of values (e.g., exactly 35 weights).
- arange() is better when using a fixed step size (e.g., every 0.5 units).

## Continue from problem statement solution

In [ ]:
# resultant array , 
# So each week starts on Monday, so weekends are at index positions [5, 6], [12, 13], [19, 20], [26, 27], and [33, 34].
avg_weight_for_each_weekend = np.zeros((5))
# avg_weight_for_each_weekend[:] =  weights[:,[-1,-2]] !! error
avg_weight_for_each_weekend
# will have to complete this befor going further

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed