## 1. What is np.random.seed()?
`np.random.seed()` sets the seed for NumPy’s pseudo-random number generator (PRNG). It makes random numbers predictable and reproducible. Without setting a seed, NumPy’s random functions generate different numbers every time you run the script.

## 2. Why Use np.random.seed()?
- **Reproducibility**: Ensures the same sequence of random numbers is generated each time the code runs.
- **Debugging**: Makes it easier to debug code since you get consistent outputs.
- **Controlled randomness**: Useful when testing models in AI/ML to compare results.

## 3. How Does it Work?
NumPy uses the Mersenne Twister algorithm, a pseudo-random number generator. The seed initializes this generator. The same seed always results in the same sequence of random numbers.

## 4. Example Usage
### Without Setting a Seed
Each time you run the following code, you will get different random numbers:

In [2]:
import numpy as np
print(np.random.randint(1, 100, 5))  # Generate 5 random integers between 1 and 100

[79 68 77 70 80]


### With np.random.seed()
Setting a seed ensures the same numbers are generated every time:

In [3]:
np.random.seed(42)
print(np.random.randint(1, 100, 5))

[52 93 15 72 61]


## 5. How It Affects Different Random Functions
Once the seed is set, all random functions will produce the same sequence on every run of a program:

In [4]:
np.random.seed(0)
print(np.random.rand(3))         # Random floats
print(np.random.randn(3))        # Standard normal distribution
print(np.random.randint(1, 10, 3))  # Random integers

[0.5488135  0.71518937 0.60276338]
[-2.2683282   1.33354538 -0.84272405]
[7 9 9]


## 6. Changing the Seed
If you change the seed, you will get a different sequence:

In [5]:
np.random.seed(7)
print(np.random.randint(1, 100, 5))

[48 69 26 68 84]


Changing the seed to 42 will produce different numbers:

In [6]:
np.random.seed(42)
print(np.random.randint(1, 100, 5))

[52 93 15 72 61]


## 7. Can You Reset the Seed?
Yes! If you call `np.random.seed()` again, it resets the generator:

In [7]:
np.random.seed(42)
print(np.random.randint(1, 100, 5))

np.random.seed(42)  # Reset to the same seed
print(np.random.randint(1, 100, 5))

[52 93 15 72 61]
[52 93 15 72 61]


## 8. What Happens If You Don’t Set a Seed?
Without `np.random.seed()`, the generated numbers will be different every time:

In [8]:
print(np.random.randint(1, 100, 5))
print(np.random.randint(1, 100, 5))

[21 83 87 75 75]
[88 24  3 22 53]


## 9. What Happens If seed=None?
Using `None` makes NumPy use the system time or entropy source:

In [9]:
np.random.seed(None)
print(np.random.randint(1, 100, 5))

[15 23 84 67 75]


## 10. Seeding for Multi-Threading & Parallel Processing
If you use NumPy in a multi-threaded environment, using the same seed across multiple threads might not guarantee reproducibility due to execution order differences. Instead, you should use:

In [12]:
rng = np.random.default_rng(42)  # New-style generator
print(rng.integers(1, 100, 5))

[ 9 77 65 44 43]


This is preferred in modern NumPy (1.17+).

## 11. Summary
| Feature | `np.random.seed()` |
|---------|--------------------|
| **Purpose** | Sets the seed for reproducibility |
| **Input** | Integer seed (None uses system entropy) |
| **Output** | Same random sequence if seed is fixed |
| **Use Cases** | AI/ML experiments, debugging, unit testing |
| **Alternative** | `np.random.default_rng(seed)` (recommended for newer NumPy) |

## 12. When Should You Use np.random.seed()?
✅ When you want reproducibility in your results.
✅ When debugging AI/ML models and need consistency.
✅ When testing algorithms that use randomness.

❌ Avoid using it globally in production unless necessary—true randomness is usually better in real-world applications.