## Problem Statement
Ten fish occupy a 5×5×5 grid of water. Each fish decides to move to a new (i, j, k) location given by the matrix below. If multiple fish end up occupying the same cell, the biggest fish eats the smaller fish. Determine which fish will survive.

In [2]:
import numpy as np

locs = np.array([
    [0,0,0],
    [1,1,2],
    [0,0,0],
    [2,1,3],
    [5,5,4],
    [5,0,0],
    [5,0,0],
    [0,0,0],
    [2,1,3],
    [1,3,1]
])

generator = np.random.default_rng(1010)
weights = generator.normal(size=10)

print(weights)


[-1.69870017  0.53799701 -0.22561399 -1.09020894  0.55391264 -1.50115445
  0.44545933  1.3448172  -1.12364327  0.21216015]


In [35]:
sorted_weights = np.argsort(weights)

unique, indices, counts = np.unique(locs,axis=0,return_index=True,return_counts=True)
print(counts)
print(np.where(counts>1)[0])

sorted_weights[::-1]

[3 1 1 2 2 1]
[0 3 4]


array([7, 4, 1, 6, 9, 2, 3, 8, 5, 0])