## Problem Statement

Eager to make your mark on the PTA, you decide the best way to hide eggs for the upcoming easter egg hunt is to use NumPy. You represent the field as a 10x10 array of 0s. Now your goal is to insert twenty random normal values at random (non-repeating) locations in the grid that tell you how much candy to hide at each spot and where.

In [31]:
import numpy as np

field = np.zeros(shape=(10, 10))
print(field)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
num_positions = 20  # Number of candies to hide

# Generate 20 unique random positions in a 10x10 grid (total 100 positions)
random_positions = np.random.choice(field.size, size=num_positions, replace=False) # replace=false ensures that no number is repeated
random_positions


array([19, 12, 88, 70, 16,  4, 72, 65,  9, 10, 84, 71, 48, 13, 66, 39,  6,
        8, 81, 32], dtype=int32)

In [33]:
# Generate 20 random normal values for the candies
rng= np.random.default_rng(7)

candy_values = np.round(rng.normal(size=20),2)  

candy_values



array([ 0.  ,  0.3 , -0.27, -0.89, -0.45, -0.99,  0.06,  1.34, -0.49,
       -0.62,  0.49,  0.36,  0.11, -0.93, -0.03,  0.7 , -1.34, -0.46,
       -1.9 , -1.29])

In [34]:
field.ravel()[random_positions] = candy_values

print(field)

[[ 0.    0.    0.    0.   -0.99  0.   -1.34  0.   -0.46 -0.49]
 [-0.62  0.    0.3  -0.93  0.    0.   -0.45  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.   -1.29  0.    0.    0.    0.    0.    0.    0.7 ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.11  0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    1.34 -0.03  0.    0.    0.  ]
 [-0.89  0.36  0.06  0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.   -1.9   0.    0.    0.49  0.    0.    0.   -0.27  0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]
