In [3]:
import numpy as np

"""
numpy.concatenate
np.concatenate() is used to join multiple arrays along a specified axis.

Parameters:
- arr1, arr2, ... : Tuple of arrays to concatenate.
- axis : The axis along which to join arrays (default is 0).
- out : Optional output array to store the result.
- dtype : Specifies the desired data type of the result.
- casting : Defines rules for casting between data types (default is 'same_kind').

Returns:
- Concatenated array. And change in array that is on 1st index
"""

# Example 1: Concatenating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result1 = np.concatenate((arr1, arr2))
print("Concatenating 1D arrays:\n", result1)  # Output: [1 2 3 4 5 6]

# Example 2: Concatenating two 2D arrays along axis=0 (rows)
arr3 = np.array([[1, 2], 
                [3, 4]])
arr4 = np.array([[5, 6], 
                [7, 8]])
result2 = np.concatenate((arr3, arr4), axis=0) # default is also 0
print("Concatenating 2D arrays along axis=0 (rows):\n", result2)

# Example 3: Concatenating two 2D arrays along axis=1 (columns)


arr5 = np.array([[1, 2],
                [3, 4]])

arr6 = np.array([[5, 6],
                [7, 8]])
result3 = np.concatenate((arr5, arr6), axis=1)
# Note: Both arrays we concatenating should have same shape, excluding the axis through which we are concatenating
print("Concatenating 2D arrays along axis=1 (columns):\n", result3)


Concatenating 1D arrays:
 [1 2 3 4 5 6]
Concatenating 2D arrays along axis=0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenating 2D arrays along axis=1 (columns):
 [[1 2 5 6]
 [3 4 7 8]]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])