- array   : [array_like]Input array. 
- values  : [array_like]values to be added in the arr. Values should be 
     shaped so that arr[...,obj,...] = values. If the axis is defined values can be of any
     shape as it will be flattened before use.
- axis    : Axis along which we want to insert the values. By default, array
     is flattened. 


- returns : [ndarray] An copy of array with values appended to the end of the array.   

In [2]:
# numpy.append() 

import numpy as np 

#Working on 1D 
arr1 = np.arange(5) 
print("1D arr1 : ", arr1) 
print("Shape : ", arr1.shape) 


arr2 = np.arange(8, 12) 
print("\n1D arr2 : ", arr2) 
print("Shape : ", arr2.shape) 


# appending the arrays 
arr3 = np.append(arr1, arr2) 
print("\nAppended arr3 : ", arr3) 


1D arr1 :  [0 1 2 3 4]
Shape :  (5,)

1D arr2 :  [ 8  9 10 11]
Shape :  (4,)

Appended arr3 :  [ 0  1  2  3  4  8  9 10 11]


In [5]:
# axis

#Working on 1D 
arr1 = np.arange(8).reshape(2, 4) 
print("2D arr1 : \n", arr1) 
print("Shape : ", arr1.shape) 


arr2 = np.arange(8, 16).reshape(2, 4) 
print("\n2D arr2 : \n", arr2) 
print("Shape : ", arr2.shape) 


# appending the arrays 
arr3 = np.append(arr1, arr2) 
print("\nAppended arr3 by flattened : ", arr3) 

# appending the arrays with axis = 0 
arr3 = np.append(arr1, arr2, axis = 0) 
print("\nAppended arr3 with axis 0 : \n", arr3) 

# appending the arrays with axis = 1 
arr3 = np.append(arr1, arr2, axis = 1) 
print("\nAppended arr3 with axis 1 : \n", arr3) 

2D arr1 : 
 [[0 1 2 3]
 [4 5 6 7]]
Shape :  (2, 4)

2D arr2 : 
 [[ 8  9 10 11]
 [12 13 14 15]]
Shape :  (2, 4)

Appended arr3 by flattened :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Appended arr3 with axis 0 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Appended arr3 with axis 1 : 
 [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [37]:
b = np.arange(16).reshape(4, 4)
columnWiseAdd = np.ones((1,4))
columnWiseAdd
print(np.append(b,columnWiseAdd,axis=0))

rowWiseAdd = np.ones((4,1))
rowWiseAdd
print(np.append(b,rowWiseAdd,axis=1))

# -----------
# same thing with concatenate
print()
print('with concatenate')
print(np.concatenate((b,rowWiseAdd),axis=1))
print(np.concatenate((b,columnWiseAdd),axis=0))
print()
# same thing with vstack and hstack
print('with vstack and hstack')
print(np.vstack((b,columnWiseAdd)))
print(np.hstack((b,rowWiseAdd)))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [ 1.  1.  1.  1.]]
[[ 0.  1.  2.  3.  1.]
 [ 4.  5.  6.  7.  1.]
 [ 8.  9. 10. 11.  1.]
 [12. 13. 14. 15.  1.]]

with concatenate
[[ 0.  1.  2.  3.  1.]
 [ 4.  5.  6.  7.  1.]
 [ 8.  9. 10. 11.  1.]
 [12. 13. 14. 15.  1.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [ 1.  1.  1.  1.]]

with vstack and hstack
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [ 1.  1.  1.  1.]]
[[ 0.  1.  2.  3.  1.]
 [ 4.  5.  6.  7.  1.]
 [ 8.  9. 10. 11.  1.]
 [12. 13. 14. 15.  1.]]
