[See this video to understand `np.argmax` and `np.argmin` method](https://www.youtube.com/live/jFBpnd0G09o?si=WiDjBsBVMXJTRU57&t=1767)

In [10]:
import numpy as np

print(np.argmax([1, 2, 3, 4, 5,6,7]))

arr = np.arange(10).reshape(2, 5)

print(arr)
np.argmax(arr, axis=1)

6
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([4, 4])

In [ ]:
# argmin is opposite

print(np.argmin([1, 2, 3, 4, 5,6,7]))



0
