[See this video to understand `np.cumsum()` and `np.cumprod()`](https://youtu.be/0mMlYbYV3dY?si=7j5V7VQdFq9R7o9o&t=3)

In [ ]:
import numpy as np

# cumulative sum
a = np.arange(1,6)
np.cumsum(a) 

array([ 1,  3,  6, 10, 15])

In [10]:
# cumulative product
np.cumprod(a)

array([  1,   2,   6,  24, 120])

In [ ]:
# 2d array
a = np.array([[1,2,3],
             [4,5,6]])
print(a)
print()

# if axis not specified it convert input array to 1d array
print(np.cumsum(a,axis=1))
print(np.cumprod(a, axis=0)) #

[[1 2 3]
 [4 5 6]]

[[ 1  3  6]
 [ 4  9 15]]
[[ 1  2  3]
 [ 4 10 18]]
