[Understand `np.flip` through this video](https://www.youtube.com/live/jFBpnd0G09o?si=vDLI2eko1UhMczdM&t=3327)

In [1]:
import numpy as np 
a = [1,7,1,2,5,7]
np.flip(a)

array([7, 5, 2, 1, 7, 1])

In [2]:
# flp both row wise and col wise a matrix
a = np.array([[1,2,3]
            ,[4,5,6]])
print(np.flip(a)) # both row wise and column wise
print(np.flip(a, axis=0))
print(np.flip(a, axis=1))

[[6 5 4]
 [3 2 1]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


[Understand `np.put` through this video](https://www.youtube.com/live/jFBpnd0G09o?si=A-wNtW8KGAUcmhJX&t=3477)

In [20]:
a = np.arange(10).reshape(5,2)
print(a)
np.put(a,ind=[1,2,-1,0],v=[77,88,99,7])
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 7 77]
 [88  3]
 [ 4  5]
 [ 6  7]
 [ 8 99]]
