## np.insert() inserts values into an array at specified positions. It does not modify the original array but returns a new one.

## Syntax:
```np.insert(arr, index, values, axis=None)```
`arr` → The original NumPy array.

`obj` → The position(s) where the value should be inserted.

`values` → The value(s) to insert.

`axis` → <br>
<pre>
     `axis` = None (default): Flattens the array before insertion.<br>
     `axis` = 0: Inserts row-wise (along columns).<br>
     `axis` = 1: Inserts column-wise (along rows).
     ...
</pre>




In [2]:
""" 🔹 Examples
1️⃣ Insert into a 1D array """
import numpy as np

arr = np.array([10, 20, 30, 40])
new_arr = np.insert(arr, 2, 25)  # Insert `25` at index `2`

print("Original:", arr)
print("After Insert:", new_arr)


Original: [10 20 30 40]
After Insert: [10 20 25 30 40]


In [1]:
# 2️⃣ Insert multiple values at different positions

arr = np.array([1, 2, 3, 4])
new_arr = np.insert(arr, obj=[1, 3], values=[99, 88])  # Insert `99` at index 1, `88` at index 3

print(new_arr)

NameError: name 'np' is not defined

In [ ]:

arr = np.array([[1, 2],
                [3, 4]])


# 3️⃣ Insert into a 2D array (axis = 0 → Insert row)
new_arr = np.insert(arr, obj=1, values=[7,7], axis=0)  # Insert a new row at index 1
print(new_arr)

[[1 2]
 [7 7]
 [3 4]]


In [ ]:
# 4️⃣ Insert into a 2D array (axis = 1 → Insert column)

new_arr2 = np.insert(arr, 1, [7, 7], axis=1)  # Insert a new column at index 1

print(new_arr2)

[[1 7 2]
 [3 7 4]]


In [ ]:
# 5️⃣ Insert without axis (Flattens array first)

new_arr3 = np.insert(arr, 2, 99)  # No axis → treats as 1D array , 99 at index 2

print(new_arr3)

[10 20 99 30 40]


array([[10],
       [20],
       [99],
       [30],
       [40]])

<pre>
🔹 Key Takeaways
✅ Does not modify the original array
✅ axis=0 → Insert row
✅ axis=1 → Insert column
✅ axis=None → Flattens first
</pre>