- [Understand `np.meshgrid()` method](https://youtu.be/7K_a1mmraHU?si=pC1LfrYO9RL8-Vqz&t=27)

In [ ]:
import numpy as np
# first array duplicate on y axis, and second array duplicates on x axis
xx, yy = np.meshgrid([7, 2, 3], [7, 5, 6])
print(xx)
print()
print(yy)

[[7 2 3]
 [7 2 3]
 [7 2 3]]

[[7 7 7]
 [5 5 5]
 [6 6 6]]


In [ ]:
# 3d plot using meshgrid -> https://youtu.be/7K_a1mmraHU?si=oZ2CRr2TAbe7haMv&t=207