[Understanding `np.repeat` from this docs](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html)

In [2]:
# Example 1: Repeating rows unequally
import numpy as np
x = np.array([[1, 2],
              [3, 4]])

# Repeat row 0 once, row 1 twice
repeated = np.repeat(x, [1, 2], axis=0)
print(repeated)


[[1 2]
 [3 4]
 [3 4]]


In [8]:
# Example 2: Repeating columns unequally

x = np.array([[1, 2],
              [3, 4]])

# Repeat col 0 once, col 1 twice
repeated_cols = np.repeat(x, [1, 2], axis=1)
print(repeated_cols)

[[1 2 2]
 [3 4 4]]


In [5]:
# 🔹 Cell 4: Flattened Repeat (Default axis=None)
# 🔧 Example 3: Repeat all elements after flattening

x = np.array([[1, 2],
              [3, 4]])

repeated_flat = np.repeat(x, [1, 2, 1, 3])
print(repeated_flat)

[1 2 2 3 4 4 4]
