In [5]:
# swapaxes
# It interchanges (swaps) the two specified axes of an array, without changing the data — just how it's viewed.

import numpy as np
arr = np.array([[1, 2],
                [3, 4]])

swapped = np.swapaxes(arr, 0, 1) # same as arr.T
# Original shape = (2, 2)
# swapaxes(0, 1) = swap rows and columns → like a transpose
print(swapped)

[[1 3]
 [2 4]]


In [ ]:
# 🔹 Cell 3: 3D Example — More Useful Case

arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])  # shape = (2, 2, 2)

print('Before swapping\n',arr3d,'\n')
print('-------------------------------------------')
""" 📌 Explanation:
Input Shape = (2, 2, 2)
We swap axis 0 and 2.

Before:
Axis 0: 2 blocks
Axis 1: 2 rows
Axis 2: 2 columns

After swapping axis 0 & 2:
Shape becomes (2, 2, 2) still, but axes are reordered.


It means:
"Swap axis 0 (blocks) with axis 2 (columns)"
In other words, we are rotating the structure so that what used to be blocks becomes columns, and what used to be columns becomes blocks.




 """

swapped3d = np.swapaxes(arr3d, 0,2)
print('After swapping\n'  ,swapped3d)
print("Original shape:", arr3d.shape)
print("Swapped shape:", swapped3d.shape)


Before swapping
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

-------------------------------------------
After swapping
 [[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
Original shape: (2, 2, 2)
Swapped shape: (2, 2, 2)
