## Key differences between np.where and np.argwhere:
- np.where(condition) returns indices as a list of arrays.

- np.argwhere(condition) returns indices as a 2D array with shape (n, 1), useful for multi-dimensional cases.

- np.where(condition, x, y) based on the condition put it in given matrice , if condition is true x value will be put, if false y value will be put

In [ ]:
# Example:
# https://www.youtube.com/live/jFBpnd0G09o?si=AyYd1vhC9MH-QNNf&t=1521

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Replace values greater than 25 with 100, and others with 0
result = np.where(arr > 25)
print(result)  # [  0   0 100 100 100]


(array([2, 3, 4]),)


In [7]:
# Another Example (Using Two Arrays):

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# If condition is True, take value from `a`, else take from `b`
result = np.where(a > 3, a, b)
print(result)  # [10 20 30  4  5]

[10 20 30  4  5]


In [8]:
# np.argwhere example

argwhere_indices = np.argwhere(arr > 25) # see it returns `n x 1`  
print("np.argwhere indices:\n", argwhere_indices)  # [[2] [3] [4]]

np.argwhere indices:
 [[2]
 [3]
 [4]]


[One more example](https://youtu.be/eClQWW_gbFk?si=v2Pj3_Vo-YBLEmqm&t=4857)