[See this video](https://youtu.be/eClQWW_gbFk?si=K_SZgSyyCs72fmYX&t=5581)

1. In NumPy, sorting is done using np.sort() or np.argsort(), but by default, sorting is ascending. To get descending order, we need to reverse the sorted array.
2. Sorting in alphabets work same as sorting in numbers.

In [33]:
import numpy as np
foo = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(np.sort(foo)) # ascending order
print(np.sort(foo)[::-1]) # descending order

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [34]:
foo.sort() # inplace sort
foo


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# 2x2 array
foo = np.array([[2, 1],
               [0, 10]])
print(foo,'\n')
print('sorted:\n',np.sort(foo),'\n')  # because default axis=1





print('In descending order\n',np.sort(foo)[:, ::-1]) 
print('In descending order\n',-np.sort(-foo))

print('Columns sorted in ascending order\n', np.sort(foo, axis=0))
print('Columns sorted in desceinding order\n', np.sort(foo, axis=0)[::-1,:]) # `:` at last is optional thing to do

[[ 2  1]
 [ 0 10]] 

sorted:
 [[ 1  2]
 [ 0 10]] 

In descending order
 [[ 2  1]
 [10  0]]
In descending order
 [[ 2  1]
 [10  0]]
Columns sorted in ascending order
 [[ 0  1]
 [ 2 10]]
Columns sorted in desceinding order
 [[ 2 10]
 [ 0  1]]


`np.argsort()` - returns the indices that would sort an array

In [36]:
# In detail -  https://youtu.be/eClQWW_gbFk?si=BsFbcOqaDzi94uUP&t=5727  
# if we wanna in descending order we can do this
arr = np.array([7,8,1,2,3,4,5,6])
sorted_arr = np.argsort(arr)
sorted_arr # so it returns the array index of sorted array elements of original array, for descending order: `sorted_arr[::-1]`

array([2, 3, 4, 5, 6, 7, 0, 1])

## Sorting a Structured Array (Sorting by Multiple Criteria)

In [52]:
# You can sort a structured array by multiple fields.


data = np.array([(1, 90), (2, 75), (3, 85)], dtype=[('id', int), ('score', int)])
sorted_data = np.sort(data, order='score')[::-1]  # Sort by 'score' in descending order
print(sorted_data)
sorted_data['score']

[(1, 90) (3, 85) (2, 75)]


array([90, 85, 75])

In [38]:
# example of if we wanna sort only one column

rng = np.random.default_rng(7)

a = rng.integers(10, size=(3, 3))
print(a,'\n')


print(np.argsort(a[:,0]))

a[np.argsort(a[:,0])] # see only the first column is sorted # 8 8 9 , rest of are still unsorted (in back its going like this a[[1,2,0]])

[[9 6 6]
 [8 5 7]
 [8 2 0]] 

[1 2 0]


array([[8, 5, 7],
       [8, 2, 0],
       [9, 6, 6]])

In [39]:
# sorting 3d array

threed_Array = np.array([[[5, 8, 3], 
                          [2, 1, 7]], 

                         [[4, 6, 2], 
                          [9, 0, 5]], 

                         [[7, 3, 1], 
                          [6, 2, 4]]])



print(np.sort(threed_Array, axis=0)) # axis 0 here is layer depth, means array will sort on layer axis
""" 
Shape: (3, 2, 3) → (3 layers, 2 rows, 3 columns)

Sorting along axis=0
Each (row, column) pair is sorted independently across all layers.

For example:

First column [[5, 2], [4, 9], [7, 6]] → [[4, 2], [5, 6], [7, 9]]    

Second column [[8, 1], [6, 0], [3, 2]] → [[3, 0], [6, 1], [8, 2]]

Third column [[3, 7], [2, 5], [1, 4]] → [[1, 4], [2, 5], [3, 7]]

# Note: It sort these like this: example of first column: 
# First Column:  [[5, 2],  
                 [4, 9],  
                 [7, 6]]
to : 

    [[4, 2],  
     [5, 6],  
     [7, 9]]

# it does same for every row


Sorted Output:

np.sort(threed_Array, axis=0)
# Output:

```
[[[4 3 1]
  [2 0 4]]

 [[5 6 2]
  [6 1 5]]

 [[7 8 3]
  [9 2 7]]]
```

Summary:

- Sorting along axis=0 means sorting each column independently, without mixing rows.
- For a 2D array, sorting along axis=0 sorts each column individually.
- For a 3D array, sorting along axis=0 sorts each row-column pair across layers. """

[[[4 3 1]
  [2 0 4]]

 [[5 6 2]
  [6 1 5]]

 [[7 8 3]
  [9 2 7]]]


' \nShape: (3, 2, 3) → (3 layers, 2 rows, 3 columns)\n\nSorting along axis=0\nEach (row, column) pair is sorted independently across all layers.\n\nFor example:\n\nFirst column [[5, 2], [4, 9], [7, 6]] → [[4, 2], [5, 6], [7, 9]]    \n\nSecond column [[8, 1], [6, 0], [3, 2]] → [[3, 0], [6, 1], [8, 2]]\n\nThird column [[3, 7], [2, 5], [1, 4]] → [[1, 4], [2, 5], [3, 7]]\n\n# Note: It sort these like this: example of first column: \n# First Column:  [[5, 2],  \n                 [4, 9],  \n                 [7, 6]]\nto : \n\n    [[4, 2],  \n     [5, 6],  \n     [7, 9]]\n\n# it does same for every row\n\n\nSorted Output:\n\nnp.sort(threed_Array, axis=0)\n# Output:\n\n```\n[[[4 3 1]\n  [2 0 4]]\n\n [[5 6 2]\n  [6 1 5]]\n\n [[7 8 3]\n  [9 2 7]]]\n```\n\nSummary:\n\n- Sorting along axis=0 means sorting each column independently, without mixing rows.\n- For a 2D array, sorting along axis=0 sorts each column individually.\n- For a 3D array, sorting along axis=0 sorts each row-column pair across la