[See this video](https://youtu.be/eClQWW_gbFk?si=K_SZgSyyCs72fmYX&t=5581)

1. In NumPy, sorting is done using np.sort() or np.argsort(), but by default, sorting is ascending. To get descending order, we need to reverse the sorted array.
2. Sorting in alphabets work same as sorting in numbers.

In [2]:
import numpy as np
foo = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(np.sort(foo)) # ascending order
print(np.sort(foo)[::-1]) # descending order

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [3]:
foo.sort() # inplace sort
foo


array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# 2x2 array
foo = np.array([[2, 1],
               [0, 10]])
print(foo,'\n')
print('sorted:\n',np.sort(foo),'\n') 





print('In descending order\n',np.sort(foo)[:, ::-1]) 
print('In descending order\n',-np.sort(-foo))

print('Columns sorted in ascending order\n', np.sort(foo, axis=0))
print('Columns sorted in desceinding order\n', np.sort(foo, axis=0)[::-1,:]) # `:` at last not required here

[[ 2  1]
 [ 0 10]] 

sorted:
 [[ 1  2]
 [ 0 10]] 

In descending order
 [[ 2  1]
 [10  0]]
In descending order
 [[ 2  1]
 [10  0]]
Columns sorted in ascending order
 [[ 0  1]
 [ 2 10]]
Columns sorted in desceinding order
 [[ 2 10]
 [ 0  1]]


`np.argsort()` - returns the indices that would sort an array

In [ ]:
# In detail -  https://youtu.be/eClQWW_gbFk?si=BsFbcOqaDzi94uUP&t=5727  
# if we wanna in descending order we can do this
arr = np.array([7,8,1,2,3,4,5,6])
sorted_arr = np.argsort(arr)
sorted_arr # so it returns the array index of sorted array elements of original array, for descending order: `sorted_arr[::-1]`

array([2, 3, 4, 5, 6, 7, 0, 1])

## Sorting a Structured Array (Sorting by Multiple Criteria)

In [ ]:
# You can sort a structured array by multiple fields.


data = np.array([(1, 90), (2, 75), (3, 85)], dtype=[('id', int), ('score', int)])
sorted_data = np.sort(data, order='score')[::-1]  # Sort by 'score' in descending order
print(sorted_data)

[(1, 90) (3, 85) (2, 75)]


In [63]:
# example of if we wanna sort only one column

rng = np.random.default_rng(7)

a = rng.integers(10, size=(3, 3))
print(a,'\n')


print(np.argsort(a[:,0]))

a[np.argsort(a[:,0])] # see only the first column is sorted # 8 8 9 , rest of are still unsorted (in back its going like this a[[1,2,0]])

[[9 6 6]
 [8 5 7]
 [8 2 0]] 

[1 2 0]


array([[8, 5, 7],
       [8, 2, 0],
       [9, 6, 6]])