## [Example of when we need to split data](https://www.youtube.com/live/XF6DCrNTzug?si=CvZ232GU4QNiCmkR&t=7065)

In [2]:
import numpy as np


In [3]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
# Split along axis=1 (columns)
split_result = np.split(a, 2, axis=1)
for i, arr in enumerate(split_result): print(f"Part {i}:\n{arr}")
split_result


Part 0:
[[0 1]
 [4 5]
 [8 9]]
Part 1:
[[ 2  3]
 [ 6  7]
 [10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

## 🔹 Explanation:
- np.split(array, sections, axis) splits equally into number of sections.

- Here, axis=1 means we're splitting columns.

- Matrix must be divisible: 4 cols ÷ 2 = 2 cols per part(section).

- You get a list of 2 arrays of shape (3, 2).

In [5]:
# np.hsplit() (Horizontal Split)
np.hsplit(a, 2)


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

## 🔹 Explanation:
- np.hsplit() = horizontal split = split along columns (axis=1).

- Equivalent to np.split(a, 2, axis=1).

- Easier and more readable than split() for column splits.



In [6]:
# np.vsplit() (Vertical Split)
vsplit_result = np.vsplit(a, 3)
for i, arr in enumerate(vsplit_result): print(f"Part {i}:\n{arr}")
vsplit_result

Part 0:
[[0 1 2 3]]
Part 1:
[[4 5 6 7]]
Part 2:
[[ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

## 🔹 Explanation:
- np.vsplit() = vertical split = split along rows (axis=0).

- a has 3 rows → can split into 3 equal parts.

- Each part is of shape (1, 4).


In [7]:
# Unequal Split (Using array_split)
print('Original Array:')
print(a , '\n')
# Works even if not divisible equally
unequal = np.array_split(a, 4, axis=1)
for i, arr in enumerate(unequal): print(f"Part {i}:\n{arr}")
unequal

Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Part 0:
[[0]
 [4]
 [8]]
Part 1:
[[1]
 [5]
 [9]]
Part 2:
[[ 2]
 [ 6]
 [10]]
Part 3:
[[ 3]
 [ 7]
 [11]]


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

## 🔹 Explanation:
- array_split allows unequal sections.
- If array can't be divided exactly, it distributes columns(or vice-versa) as evenly as possible.