[See this video clip to understand these 3 methods](https://youtu.be/eClQWW_gbFk?si=ILFs-RL5tUghOEqJ&t=5340)

In [ ]:
# np.vstack (vertical stacking) stacks arrays vertically along axis=0. This means it expects all input arrays to have the same number of columns (i.e., same second dimension for 2D arrays).
# Its worth to note : vstack automatically converts 1D arrays into row vectors ((1, n)) before stacking, where n is the value of axis of other arrays, if other array is also 1d then, `n` is 2 

# by vertical stacking, rows remains same, but columns are added to the resultant array.

import numpy as np
foo = np.array(['a', 'b'])
bar = np.array(['c', 'd'])
baz = np.array(['e', 'f'])
bingo = np.array(['g', 'h', 'i'])
bongo = np.array([
    ['j', 'k'],
    ['l', 'm']
])
bongos = np.array([
    ['j', 'k'],
    ['l', 'm']
])

np.vstack((foo, bar,bongo))

array([['a', 'b'],
       ['c', 'd'],
       ['j', 'k'],
       ['l', 'm']], dtype='<U1')

In [3]:
# hstack

# Non-Error scenario
""" 
foo, bar, baz are 1D (2,), but NumPy treats them as (1,2)
Since they all have 1 row, they stack fine → result shape (1, 6)
"""


print(np.hstack([foo, bar, baz]))


# Erorr scenario
""" Why Does hstack([foo, bongo]) Throw an Error?
foo is (2,) (i.e., (1,2) when stacked)

bongo is (2,2)

Row counts don't match (1 ≠ 2) """
# np.hstack([foo, bongo])  #! Error


['a' 'b' 'c' 'd' 'e' 'f']


" Why Does hstack([foo, bongo]) Throw an Error?\nfoo is (2,) (i.e., (1,2) when stacked)\n\nbongo is (2,2)\n\nRow counts don't match (1 ≠ 2) "

In [4]:
# np.stack join a sequence of arrays along a new axis, The axis parameter specifies the index of the new axis in the dimensions of the result
""" Syntax
np.stack(arrays, axis=0)
 """

""" Parameters
1. arrays → A list/tuple of arrays with the same shape.
2. axis (default = 0) → The axis in the result array along which the input arrays are stacked.. 
3. out -> The out parameter allows you to store the result in a preallocated array instead of creating a new one.
"""

""" 
np.stack() increases the dimensionality by introducing a new axis. If you start with:
Means:
1D arrays → Produces a 2D array

2D arrays → Produces a 3D array

3D arrays → Produces a 4D array, and so on.
 """

# The axis parameter decides where the new axis is added.


a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])  

# Preallocate an array of the correct shape
out_array = np.empty((2,3), dtype=int)

# Store the result in `out_array`

# Example: axis=0 means a new dimension is added at index 0, and this means that the new axis is inserted at position 1 in the shape tuple.
# The new axis is added in the resultant array's shape, not in the original arrays. The original arrays remain unchanged in memory.

np.stack([a, b], out=out_array,axis=0)

# Breaking It Down:
""" 
Original arrays:
- a: Shape (3,) → [1, 2, 3]
- b: Shape (3,) → [4, 5, 6]
- Resultant array after stack(axis=1):
- New axis is added at index 1 in the resultant shape.
- Resulting shape becomes (3,2), meaning:
- 3 rows (from the original arrays)
- 2 columns (one from a, one from b).

- So we can also say Resulting shape depends on where the new axis is inserted.
 """

print(out_array)

# here a and b array both get new axis, promoting them from 3, array to (3,1) and then they got stack along that new axis
print(np.stack([a, b],axis=1)) # vs print(np.hstack([a,b])) # out: [1,2,3,4,5,6] , this is because np.stack introduce new axis every

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
