In [1]:
import numpy as np
rng = np.random.default_rng(7)
arr = rng.integers(0,100,size=(3,3))
arr

array([[94, 62, 68],
       [89, 57, 77],
       [83, 22,  5]])

In [2]:
# mean
print(arr.mean())  # mean of all elements
print(arr.mean(axis=0))  # mean of each column
print(arr.mean(axis=1))  # mean of each row

61.888888888888886
[88.66666667 47.         50.        ]
[74.66666667 74.33333333 36.66666667]


In [3]:
# median, means first it sort each row or column and then take the middle value on given axis 
print(np.median(arr))  # median of all elements in this case, numPy flattens the array into a 1D list and then computes the median of that list.
print(np.median(arr, axis=0))  # median of each column
print(np.median(arr, axis=1))  # median of each row

68.0
[89. 57. 68.]
[68. 77. 22.]


In [12]:
# ⚙️ NumPy Standard Deviation Functions
# ✅ Basic usage:

import numpy as np

data = [10, 12, 23, 23, 16, 23, 21, 16]
print(np.std(data))  # Population SD(population standard deviation) (default)

# ✅ For sample SD(sample standard deviation), use ddof=1 (degrees of freedom = 1):
print(np.std(data, ddof=1))  # Sample SD(sample standard deviation)
# ddof=0 → divide by n → population SD

# ddof=1 → divide by n-1 → sample SD



4.898979485566356
5.237229365663817
