[See this video for understanding](https://youtu.be/eClQWW_gbFk?si=ed8IV7X_j4TpXSPX&t=5837)

In [2]:
import numpy as np
gar = np.array([1, 2, 3, 4, 5, 6, 7,10,10 ,9]) 
print(np.unique(gar)) # so with removing duplicates it also sorts the array

[ 1  2  3  4  5  6  7  9 10]


In [3]:
alphabets = np.array(['b','b','a','a','c','c'])
print(np.unique(alphabets)) # also sorts

['a' 'b' 'c']


In [4]:
print(np.unique(alphabets,return_inverse=True)) # this explained in next cell of next cell

chars,indices = np.unique(alphabets,return_index=True) # return index also, of sorted elements first occurence
print(chars)
print(indices)

(array(['a', 'b', 'c'], dtype='<U1'), array([1, 1, 0, 0, 2, 2]))
['a' 'b' 'c']
[2 0 4]


In [ ]:
# remove duplicates, but let's say we wanna keep order same 

unique = np.array(['b','b','a','a','c','c'])
uniqueness = np.unique(unique,return_index=True)
print(uniqueness)
print(uniqueness[1]) # means  first item of uniqueness comes from index 2 , second item of uniqueness comes from index 0, third item of uniqueness comes from index 4
print(np.sort(uniqueness[1]))
unique = unique[np.sort(uniqueness[1])]
print(unique) # reorder the elements in the same order they occur

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 0, 4]))
[2 0 4]
[0 2 4]
['b' 'a' 'c']


In [ ]:

# Understanding `return_inverse` param
locs = np.array([
    [0,0,0],
    [1,1,2],
    [0,0,0],
    [2,1,3],
    [5,5,4],
    [5,0,0],
    [5,0,0],
    [0,0,0],
    [2,1,3],
    [1,3,1]
])


print(np.unique(locs,axis=0,return_inverse=True)[1])

unique_locs = [
    [0, 0, 0],  # Index 0
    [1, 1, 2],  # Index 1
    [1, 3, 1],  # Index 2
    [2, 1, 3],  # Index 3
    [5, 0, 0],  # Index 4
    [5, 5, 4]   # Index 5
]

# np.unique does sorting here lexicographically
""" Lexicographic sorting means it compares row elements from left to right, similar to how words are sorted in a dictionary.

First, it sorts based on the first column.

If there are ties in the first column, it then sorts based on the second column.

If there's still a tie, it sorts based on the third column.
"""

""" 
Before sorting, it remove duplicates:

[0,0,0]
[1,1,2]
[1,3,1]
[2,1,3]
[5,0,0]
[5,5,4]
 """

# then : 
""" Step 2: Sort Lexicographically
Sorting is done column by column:

1. First column:


0 → [0,0,0]
1 → [1,1,2], [1,3,1]
2 → [2,1,3]
5 → [5,0,0], [5,5,4]

2. For same first-column values, sort by second column:

1,1,2 vs 1,3,1 → 1,1,2 comes first.

5,0,0 vs 5,5,4 → 5,0,0 comes first.

3. Final sorted unique array:


[
    [0, 0, 0],  # Index 0
    [1, 1, 2],  # Index 1
    [1, 3, 1],  # Index 2
    [2, 1, 3],  # Index 3
    [5, 0, 0],  # Index 4
    [5, 5, 4]   # Index 5
]

 """


# And this is why np.unique(locs, axis=0, return_inverse=True)[1] returns:
# [0, 1, 0, 3, 5, 4, 4, 0, 3, 2]
# Each row in locs is mapped to its lexicographically sorted unique index.
# ---------------------------------------------------

""" 
# return_inverse
Now, the inverse array [0, 1, 0, 3, 5, 4, 4, 0, 3, 2] means:

The 1st row of locs ([0,0,0]) → Index 0 in unique_locs.

The 2nd row of locs ([1,1,2]) → Index 1 in unique_locs.

The 3rd row of locs ([0,0,0]) → Index 0 in unique_locs.

The 4th row of locs ([2,1,3]) → Index 3 in unique_locs.

The 5th row of locs ([5,5,4]) → Index 5 in unique_locs.

The 6th row of locs ([5,0,0]) → Index 4 in unique_locs.

The 7th row of locs ([5,0,0]) → Index 4 in unique_locs.

The 8th row of locs ([0,0,0]) → Index 0 in unique_locs.

The 9th row of locs ([2,1,3]) → Index 3 in unique_locs.

The 10th row of locs ([1,3,1]) → Index 2 in unique_locs.
 """



[0 1 0 3 5 4 4 0 3 2]


' \nNow, the inverse array [0, 1, 0, 3, 5, 4, 4, 0, 3, 2] means:\n\nThe 1st row of locs ([0,0,0]) → Index 0 in unique_locs.\n\nThe 2nd row of locs ([1,1,2]) → Index 1 in unique_locs.\n\nThe 3rd row of locs ([0,0,0]) → Index 0 in unique_locs.\n\nThe 4th row of locs ([2,1,3]) → Index 3 in unique_locs.\n\nThe 5th row of locs ([5,5,4]) → Index 5 in unique_locs.\n\nThe 6th row of locs ([5,0,0]) → Index 4 in unique_locs.\n\nThe 7th row of locs ([5,0,0]) → Index 4 in unique_locs.\n\nThe 8th row of locs ([0,0,0]) → Index 0 in unique_locs.\n\nThe 9th row of locs ([2,1,3]) → Index 3 in unique_locs.\n\nThe 10th row of locs ([1,3,1]) → Index 2 in unique_locs.\n '

In [ ]:


# What can be done with this `return_inverse` param, we can reconstruct the original array

unique_locs, inverse = np.unique(locs, axis=0, return_inverse=True)

print("Unique Rows:")
print(unique_locs)

print("\nInverse Mapping (Original -> Unique):")
print(inverse)

print("\nReconstructed Original from Unique:")
print(unique_locs[inverse])

Unique Rows:
[[0 0 0]
 [1 1 2]
 [1 3 1]
 [2 1 3]
 [5 0 0]
 [5 5 4]]

Inverse Mapping (Original -> Unique):
[0 1 0 3 5 4 4 0 3 2]

Reconstructed Original from Unique:
[[0 0 0]
 [1 1 2]
 [0 0 0]
 [2 1 3]
 [5 5 4]
 [5 0 0]
 [5 0 0]
 [0 0 0]
 [2 1 3]
 [1 3 1]]
