## We can delete numpy array elements using np delete function
[Understand `np.delete` through this video](https://www.youtube.com/live/jFBpnd0G09o?si=cB9oiOaBX-sjDqDV&t=3577)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
rng = np.random.default_rng(42)

a = rng.integers(10, size=(3, 4))
a

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9]])

In [7]:
print(a)
np.delete(a, 1, axis=0)

[[0 7 6 4]
 [4 8 0 6]
 [2 0 5 9]]


array([[0, 7, 6, 4],
       [2, 0, 5, 9]])

In [5]:
print(a)
np.delete(a, 0, axis=1)

[[0 7 6 4]
 [4 8 0 6]
 [2 0 5 9]]


array([[7, 6, 4],
       [8, 0, 6],
       [0, 5, 9]])

In [6]:
print(a)
np.delete(a, (0,2), axis=1)

[[0 7 6 4]
 [4 8 0 6]
 [2 0 5 9]]


array([[7, 4],
       [8, 6],
       [0, 9]])