## We can delete numpy array elements using np delete function

In [16]:
import numpy as np
rng = np.random.default_rng(42)

a = rng.integers(10, size=(3, 4))
a

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9]])

In [17]:
np.delete(a, 1, axis=0)

array([[0, 7, 6, 4],
       [2, 0, 5, 9]])

In [18]:
np.delete(a, 0, axis=1)

array([[7, 6, 4],
       [8, 0, 6],
       [0, 5, 9]])

In [19]:
np.delete(a, (0,2), axis=1)

array([[7, 4],
       [8, 6],
       [0, 9]])

In [52]:
import numpy as np

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

sales_data[:,1:]


# np.max(sales_data[:,1:], axis=0)
np.mean(sales_data[:,1:], axis=1)

# make 2 vectors
vec1 = np.array([1, 2, 3, 4, 5])
vec2 = np.array([10, 20, 30, 40, 50])
vec1 @ vec2


np.int64(550)