vectorize is used to apply a function to each element of an array

In [50]:
# Example
import numpy as np
import time
import numpy as np

timeit = time.time()

def slow_func(x):
    if x % 2 == 0:
        return x * 2
    else:
        return -x

vfunc = np.vectorize(slow_func)

arr = np.arange(1_000_000)
result = vfunc(arr)

print(result)
print("Execution time:", time.time() - timeit)


[      0      -1       4 ... -999997 1999996 -999999]
Execution time: 0.1882493495941162


In [51]:
# faster alternatives is numba or np.where
from numba import njit
import numpy as np
import time

timeit1 = time.time()

@njit
def fast_func(arr):
    result = np.empty_like(arr)
    for i in range(arr.size):
        if arr[i] % 2 == 0:
            result[i] = arr[i] * 2
        else:
            result[i] = -arr[i]
    return result

arr = np.arange(1_000_000)
result = fast_func(arr)

print(result)
print("Execution time:", time.time() - timeit1)


[      0      -1       4 ... -999997 1999996 -999999]
Execution time: 0.13185620307922363


In [52]:

import time 
timeit2 = time.time()
arr = np.arange(1_000_000)
result = np.where(arr % 2 == 0, arr * 2, -arr)
print(result)
print("Execution time:", time.time() - timeit2)

[      0      -1       4 ... -999997 1999996 -999999]
Execution time: 0.023250818252563477


# Vectorize explained in detail :

🔹 **What is `np.vectorize()`?**  
`np.vectorize()` is a convenience function that allows you to apply a scalar function (a function that works on single values) element-wise to arrays, without writing loops.

It essentially creates a vectorized wrapper around your function, enabling it to work with NumPy arrays as inputs.

---

🔹 **Syntax**
```python
np.vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
```

---

🔸 **Parameters Explained**

| Parameter   | Description |
|-------------|-------------|
| `pyfunc`    | The Python function you want to apply element-wise. |
| `otypes`    | A string of output types (e.g., `'i'` for int, `'f'` for float, `'O'` for object). |
| `doc`       | *(Optional)* A custom docstring for the returned function. |
| `excluded`  | A set or sequence of argument indices or names to exclude from vectorization. |
| `cache`     | If `True`, results are cached. Useful for expensive and repeated computations. |
| `signature` | A NumPy generalized ufunc signature (for more complex vectorization, like matrix operations). |

---

🔹 **Basic Example**

**Scalar function:**
```python
def add_one(x):
    return x + 1
```

**Vectorize it:**
```python
import numpy as np

vfunc = np.vectorize(add_one)
arr = np.array([1, 2, 3])
print(vfunc(arr))  # Output: [2 3 4]
```

---

🔸 **Using `otypes`**

If the return type isn't obvious (especially with empty arrays), specify it with `otypes`.

```python
def stringify(x):
    return str(x) + "!"

vfunc = np.vectorize(stringify, otypes=['O'])  # O = Object (string)
print(vfunc([1, 2, 3]))  # Output: ['1!' '2!' '3!']
```

---

🔸 **Using `excluded`**
```python
def power(base, exponent):
    return base ** exponent

vec_power = np.vectorize(power, excluded=['exponent'])  # Keep exponent fixed
print(vec_power([1, 2, 3], exponent=2))  # Output: [1 4 9]
```

---


In [53]:
def stringify(x):
    return str(x) + "!"

vfunc = np.vectorize(stringify, otypes=[str])  # or O = Object (string)
print(vfunc([1, 2, 3]))  # Output: ['1!' '2!' '3!']

['1!' '2!' '3!']


In [58]:
def power(base, exponent):
    return base ** exponent

vec_power = np.vectorize(power, excluded=['exponent'])  # Keep exponent fixed, but excluded is not such required here
print(vec_power([1, 2, 3], exponent=2))  # Output: [1 4 9]

[1 4 9]
