# Numpy is a fundamental library for scientific computing in Python. It provides a powerful and efficient way to work with arrays and matrices in Python.

## Advantages of using numpy arrays over python lists :

### 1. Numpy arrays are faster than python lists.
### 2. Numpy arrays are more memory efficient than python lists, as they consume less memory.

## Basic difference between arrays and lists :
###  List : Comma separated values , Numpy array : Non-comma separated values 


## numpy provides enormous amount of math functions that operate on these arrays or matrices.


## importance of numpy  : 
### math logical , shape manipulation , sorting , I/O discrete fourier transforms, basic linear algebra , basic statistics operations,random simulation and much more . 




In [ ]:
# see this video clip to see how objects are actually stored in memory and retrieve from it: https://youtu.be/eClQWW_gbFk?si=k0MEtAMWHcJ42QsS&t=226 by GormAnalysis

# numpy vs python lists comparison on every basis - https://www.youtube.com/live/40xGMygHMDU?si=Sir1jrEgWbxMCAOf&t=457

import numpy as np
# numpy arrays are intended to store objects with same type and size : because : https://youtu.be/eClQWW_gbFk?si=NqZZjgqHEmRFrNxc&t=216

""" 2 basic rules for  every numpy arrays 
1. Every element in the array must be of the same type and size
2. If an array elements are also arrays , those inner arrays must have the same type and number of elements as each other
 """
print(type(np.array([1, 2, 3])))# <class 'numpy.ndarray'> --> means some n-dimentional array
# numpy arrays must contain same type and dimension of data 
# to check type of data in numpy array
print(np.array([1, 2, '3',True])) , # in this case numpy not gives error , instead it type cast all elements to string in order to satisfy the rule that every element in the array must be of the same type and size

# to create 2d array
arr_2d = np.array([
    [1, 2, 3], 
    [4, 5, 6]
    ])
print(arr_2d.ndim) # 2 , means 2d array
print(arr_2d.shape) # means 2 rows and 3 columns

# So you can make 2d array of list of list , and 3d array of list of list of list ..., so on . 

print(len(arr_2d)) # 2 , because arr_2d only contains 2 elements (list of lists) directly inside of itself
""" 
now you may suprise that is it only have 2 elements ? As it giving only 2 instead of giving 6 . Yes ,  Because the arr_2d is considered as an array that contains only 2 arrays inside of it 
basically it only contains 2 values that is here list , so you shouldn't be confused in this case as same behaviour also showed by all iterables in python
"""
# if you wanna get the total number of elements in the nested array , you should use `size` attribute
""" 
- .shape tells you the dimensions (rows, columns, depth, etc.).
- It returns a tuple that represents the size of each axis.
- The length of the tuple = number of dimensions.
Example : (2, 3)  # 2 rows, 3 columns
"""


print(arr_2d.size) 
""" 2️⃣ .size → 
- Total Number of Elements
- .size gives the total count of elements in the array.
- It is simply the product of the size of all dimensions.
Example : 2(size of row) * 3(size of column) = 6 elements in total in array
"""



print(arr_2d.dtype) # to see which type of data is stored in numpy array use `dtype`


# Now you might also wondering we thought that we can't have a array of strings because string are objects that vary in sizes , and whole point of array is to store fixed size object
# See this clip to find answer to this question : https://youtu.be/eClQWW_gbFk?si=4J07kYP2bT_LAr9x&t=632


<class 'numpy.ndarray'>
['1' '2' '3' 'True']
2
(2, 3)
2
6
int32


In [11]:
# There is also called itemsize, which tells how many bytes each element in the array takes up in memory.
# For example, if the itemsize is 8, it means each element in the array takes up 8 bytes of memory.
import numpy as np
# Create a NumPy array of integer type elements
arr = np.array([1, 2, 3, 4])
print(arr.itemsize)  # Output: 8 (for int64, which is the default integer type in NumPy on most systems)
# Create a NumPy array of string type elements
arr_string = np.array(["snow", "fire", "ice"])
print(arr_string.itemsize)  # Output: 8 (for float64, which is the default float type in NumPy on most systems)

8
16


In [6]:
# Arrays are mutable in numpy, so to make specific array read only
a = np.arange(10)
a.setflags(write=False)
# a[0] = 1 #! Error 
a.flags

[]


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [15]:
# Changing the data type of numpy array
a = np.array([7.10, 2.1, 3, 4], dtype=np.float32)
# after creating the array, you can change the data type of the array using the astype() method
a = a.astype(np.int32)  # Change to int32
print(a.dtype)  # Output: float32
print(a)  # Output: [1 2 3 4]


int32
[7 2 3 4]


## Think of 1 dimension as row of numbers and 2 dimension as matrix , we talk about higher dimensions later 

In [6]:
# Basic matrix 

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]
    ])
print(matrix)
# check dimension 
print(matrix.shape) # means 3 rows and 3 columns ,but note : this is a 2d array as 1 block depth(array and vectors are not same in numpy)
# arrays dimension are define by number of brackets
print(matrix.ndim) # means 2d array  , for check array dimension

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


#### list vs numpy array speed comparision


In [7]:
%timeit [_ for _ in range(1000)]

21.2 µs ± 727 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:

import numpy as np
%timeit np.arange(1000)*2 # np.arange is used to create an array with range of numbers , here 0-999  and then we scale it by 2 , basically create 1000 dimensional vector , but note : this is a 1d array

1.92 µs ± 75.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
%timeit np.array([_ for _ in range(1000)])*2 # its very silly thing to do why, just see the time comparison

69.7 µs ± 5.12 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Why this happened even (np.arange takes very less time than above code , although we are creating an numpy array in both cases)
#### The key difference between the two operations lies in how the arrays are created:
- 1️⃣ `np.arange(1000)` creates a NumPy array efficiently in C without using Python loops.As python loops are obviously very slow. Full Syntax : `np.arange(start,stop,step,dtype)` 
- Multiplication is applied directly on the NumPy array, utilizing vectorized operations optimized with low-level C implementations.

- 2️⃣ `np.array([_ for _ in range(1000)]) * 2`
- [ _ for _ in range(1000) ] first creates a Python list using list comprehension.
- np.array(...) then converts the list into a NumPy array, which adds overhead.
- Multiplication is then performed, but the overhead of list creation + conversion makes this approach significantly slower.

##### So Why is np.arange(1000) faster?
- Avoids Python loops: np.arange(1000) is implemented in C, making it much faster than list comprehension.
- No intermediate list creation: np.array([_ for _ in range(1000)]) first creates a Python list in memory, then converts it to a NumPy array, which is an extra step.
- Memory efficiency: np.arange(1000) directly creates an array with efficient memory layout, while the list-comprehension method involves unnecessary memory allocation.



In [10]:
a= np.array([[1,2,4] ,[2,3,4]])


In [11]:
# code to create matrix with user input
row = int(input("Enter row number: "))

col = int(input("Enter col number: "))

input_Matrix = np.zeros((row, col),dtype=int) # # np.zeros is used to create a array of specified size with 0 as all values
print(input_Matrix)

for i in range(row):
    for j in range(col):
        input_Matrix[i][j] = int(input(f"Enter value for {i+1} row and {j+1} column: "))

print(input_Matrix)

[[0 0]
 [0 0]]
[[1 0]
 [0 1]]


In [26]:
# see np.tile -> https://youtu.be/xfNHRJIGOPQ?si=gJUkGa-1RRSRONm5&t=180
import numpy as np
a = np.arange(10)
print(np.tile(7,a.shape))
print(np.tile(np.array([[1,2,3],[4,5,6]]),(3,3)))

print(np.tile([[1,2],[3,4]],(5,10)))
f =  np.tile([[1,2],[3,4]],(5,10,1,1)) # if you wanna keep the dimensions same
print(f.shape)
f

[7 7 7 7 7 7 7 7 7 7]
[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]
[[1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]]
(5, 10, 2, 2)


array([[[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]],


       [[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]],


       [[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
       

In [12]:
print(np.full((7,7),2)) # np.full is used to create a array of specified size with specified value
print(np.full(2,2)) 

print(np.size(np.full(2,2))) # to check how many elements are there in the array

[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]
[2 2]
2


### A simple mean program using numpy
#### In statistics, the mean (specifically, the arithmetic mean) is the most common type of average, calculated as:
- Mean = ∑x / n  : where ∑x is the sum of all x values in the dataset, n is the number of x values.


In [13]:

%%timeit
# let's say we have a data of stock prices of every second of 1 year , those stocks increase gradaully , and we wanna find the average price of the stocks in a year
# we do this using numpy 
import numpy as np
stock_price = 100 + np.arange(60*60*24*365) /100 # this will create an array of 60*60*24*365 elements , means 60*60*24*365 seconds , basically total number of seconds in a year
""" we do this (divide each element by 100 and then add 100) 
because : 
100 + 0 / 100 = 100.00 
100 + 1 / 100 = 100.01
100 + 2 / 100 = 100.02
100 + 3 / 100 = 100.03
100 + 4 / 100 = 100.04
100 + 5 / 100 = 100.05
to simulate that stock price is increasing gradually , this creates a gradually increasing stock price dataset where each value is slightly larger than the previous one.
It helps in simulations or testing algorithms where stock prices need to be smoothly increasing. """
# now to find average price of the stocks in a year (to simulate this formula , where : ∑x / n , :∑x(Sigma x) is sum of all x elements / n(here size of array))

np.mean(stock_price)


     

273 ms ± 17.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
%%timeit
"""A normal python code for doing that we did above using numpy"""
stock_price = []
for i in range(60*60*24*365): 
    stock_price.append(100 + i / 100)

print(sum(stock_price) / len(stock_price))
""" Caution: It will take lot of time , and compute"""
# see time comparison as compare to above cell

157779.995
157779.995
157779.995
157779.995
157779.995
157779.995
157779.995
157779.995
3.27 s ± 306 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
# to create array with random values
import numpy as np
np.random.random((3,3))

# to create array with specified range of random values

np.random.randint(low=1, high=7, size=(2,3),dtype=int) # 1 inclusive and 7 exclusive , and you can interpret it like 2 iterations of rolling 3 dice

# to create array of n number of random floats
print(np.random.rand(10)) # create array of 10 random floats

[0.62902157 0.50655436 0.63359535 0.05367764 0.12143043 0.01815037
 0.70095984 0.94126965 0.08170842 0.99938307]


In [16]:
# Arrays are mutable so we can change its element after creation 

arr = np.array([1, 2, 3])
arr[0] = 10
print(arr)
%store arr

# we can also access multiple elements at once


[10  2  3]
Stored 'arr' (ndarray)


In [17]:
# Doing indexing in arrays
%store -r arr
arr2 = np.array([1, 2, 3, 4, 5])
print(arr[[0,-1,-2]])
print(arr[np.zeros(3,dtype='int64')]) # to access multiple elements at once , we can even use array for that also

print(arr2[2:]) # 2 to length-1 , so indexing in array is same as indexing in normal iterables of python

[10  3  2]
[10 10 10]
[3 4 5]


In [18]:
# We can also use fill method in array object

arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)
arr2.fill(0) # fill all the elements with 0
print(arr2)

[1 2 3 4 5]
[0 0 0 0 0]


In [19]:
# assigning values to multiple indexes at once

arr2[[0, 2]] = 10 # assign value 10 to all elements it selects (0 and 2)
print(arr2)

arr2[[0,2]] = [100,200] # assign values 100 and 200 to elements 0 and 2
print(arr2)


[10  0 10  0  0]
[100   0 200   0   0]


In [ ]:
# no-zero methods, returns indexes of non-zero elements
arr2 = np.array([1, 2, 3, 0, 0, 0, 4])
print(np.nonzero(arr2))

# In array of Tuple and False, it consider False values as 0s

(array([0, 1, 2, 6]),)


In [1]:
# For identity matrix
import numpy as np
identity_matrix = np.eye(3) # or np.identity(3) # create identity matrix, of 3x3
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
