In [2]:
# indexing multiDimensionalArrays

import numpy as np

# %store np
# indexing 2d array
arr = np.array([
    # --------- axis 1(column axis) --------- 
    [1, 2, 3],    # #
    [4, 5, 6],    # --------- axis 0(row axis) ---------
                  # #
])
print(arr.ndim) # so its a 2d array
print(arr) 

2
[[1 2 3]
 [4 5 6]]


In [ ]:
# before we indexing array its important to understand its structure
# see this clip -  https://youtu.be/eClQWW_gbFk?si=vWTfD12i-nyfmLhE&t=1419

# so if you wanna get full entire row (first element of arr)
print('first row:',arr[0]) # or arr[0,None] means also the same , says : first row 

# now if you wanna get first element of first row
print('first element of first row:',arr[0][0])
# last element of first row
print('last element of first row:',arr[0][2])
# last element of last row
print('last element of last row:',arr[1][2]) # or arr[][-1][-1]

"""
means give us first element arr , but since we give it None(Default is also None) after `,` 
we saying inside that give all the elements of that selected element 
"""
arr[0,None] 


# Note:We have 2 syntaxes for indexing
arr[0,1] # first row , 2nd element
# For list representation we can use this :

""" using this syntax we can dynamically select any elements of an array, n number of times,but note: it give elements in 
list even you select 1 element only, its also called fancy indexing"""


# More about fancy indexing - https://www.youtube.com/live/40xGMygHMDU?si=nKaa7aiovhwU6BWz&t=1437
print(arr[[1,0],[0,1]]) # means give me 1st element(index 0) of 2nd row and 2nd element(index 1) of 0th row
print(arr[[0] , [1,2,0,1]]) # of 0th row give elements at index 1,2,0,1[yes we can index elements repeatedly also, using this syntax]


first row: [1 2 3]
first element of first row: 1
last element of first row: 3
last element of last row: 6
[4 2]
[2 3 1 2]


In [4]:
# and we can also combine slicing lists,list of indices , negative indexing   , like this:
"""
arr[0:1,[1,2]] so this is also doing same , saying: give me a value from 0th element to 1st element(1st is exclusive) of arr 
and inside it f, give last and first element of it 
"""
print(arr[0:1,[-1,1]])  


[[3 2]]


In [5]:
# So now let's say we wanna swap rows of any 2d array

arr = np.array([
    # --------- axis 1(column axis) ---------
    [1, 2, 3],    # #
    [4, 5, 6],    # --------- axis 0(row axis) ---------
                  # #
])
# LHS                            assign to            # RHS
# arr selects all the elements                        # arr selects all the elements but in reverse             
arr[:] = arr[::-1]
print(arr)

[[4 5 6]
 [1 2 3]]


In [6]:
# Let's we have any matrix , we wanna make its diagonal elements 0

arr = np.array([
    [1, 2, 3],  
    [4, 5, 6],
    [7, 8, 9]           
])

# so in this way we can select multiple elements of arr individually , to access their distinct elements

# row 0,1,2, for row 0 element 0 , for row 1 element 1 , for row 2 element 2 ,  access and assign them 0
arr[[0,1,2], [0,1,2]] = 0
print(arr)


[[0 2 3]
 [4 0 6]
 [7 8 0]]


## So we talk about 2d arrays , but what about 3d and above dimensional Arrays ? 
- How you should interpret them in your mind ? [See this clip](https://youtu.be/eClQWW_gbFk?si=ZYjXdOMjMIZzxL1K&t=1611)

In [12]:
# So now comes 3d Array !! Think of 3d array as row of matrices 

arr_3d = np.array(

       [
        #    1st row
           [
            #    matrix of 1st row
               [1,2,3],
               [3,4,3]

           ],
         # 2nd row
           [
            #    matrix of 2nd row
               [5,6,2],
               [7,8,2]
           ]

       ]

)
print(arr_3d.ndim) # 3

arr_3d.shape # (2,2,3) means 2 rows(matrices) , inside those 2 rows there are 2 rows, inisde those 2 rows there are 3 columns (so we go from most outer to most inner)


3


(2, 2, 3)

In [8]:
# Now indexing in 3d array 
""" Watch this clip : https://youtu.be/eClQWW_gbFk?si=o-Uj1mvWApwu4IJp&t=1657 , this will improve your understanding
how to think of indexing in 3d array """


# Now let's say we wanna swap these matrices(rows of matrix that is inside arr_3d)
""" so first it select all rows of arr_3d(which contains matrix) and on RHS (the value that assigned to arr_3d) , 
selects all rows of arr_3d but in reverse """

arr_3d[:] = arr_3d[::-1] 
print(arr_3d)

[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


In [9]:
# Let's see one more example , that give us intution of indexing in 3d array

""" let's say we wanna swap last row of first matrix that is inside of first row and that first row is
inside of arr_3d , to last row of last matrix that is inside last row and that last row is inside of arr_3d
"""

arr_3d[:, [-1]] = arr_3d[::-1, [-1]]
print(arr_3d)

[[[5 6]
  [3 4]]

 [[1 2]
  [7 8]]]


In [1]:
import numpy as np
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])