## Broadcasting in arrays

[What is BroadCasting, see this clip by `GormAnalysis`](https://youtu.be/eClQWW_gbFk?si=_p78st0bKeELtEcl&t=2485)

[BroadCasting Rules](https://youtu.be/eClQWW_gbFk?si=yW_lHKlO6Htdhrp_&t=2555)<br>
**For example suppose we want to add two arrays, A and B**
- Moving backwards from the last dimension of each array, we check if their dimensions are compatible
- Dimensions are compatible if they are equal or either of them is one 
- If all of A's dimensions are compatible with B's dimensions, or vice versa. they are compatible arrays
- [Click here for Examples](https://youtu.be/eClQWW_gbFk?si=wIHKB0LHH0HkBpCG&t=2590)


In [2]:
import numpy as np
np.array([
    [1,2,5],
    [3,4,9]
]) + 1

array([[ 2,  3,  6],
       [ 4,  5, 10]])

[Watch this clip to know about newaxis in numpy](https://youtu.be/eClQWW_gbFk?si=MIbVGQl0Do2Pm6qj&t=2780)

In [3]:
# So basically we have an 2 arrays :
"""
1st array: (1,4) - [3,11,4,5]

2nd array: (1,3) - [5,0,3]

So basically we have we have to perform subtraction between these two arrays:
------------------------------------------------------------------------------ 

"""


first_array = np.array([
    3,11,4,5
])
print('First array:\n',first_array)
second_array = np.array([5,0,3])
print('Second array:\n',second_array)

# After reshaping

print('After reshaping first array:\n',first_array.reshape(4,1)) # means reshape to 4 rows and 1 column
print('Subtraction:\n',first_array.reshape(4,1) - second_array) 
# How this subtraction is done by numpy, you can see that it here for visualizing - https://youtu.be/eClQWW_gbFk?si=XUItmV2HlJu9NFx7&t=2807

First array:
 [ 3 11  4  5]
Second array:
 [5 0 3]
After reshaping first array:
 [[ 3]
 [11]
 [ 4]
 [ 5]]
Subtraction:
 [[-2  3  0]
 [ 6 11  8]
 [-1  4  1]
 [ 0  5  2]]


using `np.newaxis` or `None` for broadcasting

In [4]:
# We can also 
# first_array[:, None] inserts a new axis, converting it into a 2D column vector with shape (4, 1).
# None is used as an alias for np.newaxis, which tells NumPy to add an extra dimension.
# so we can also use this way to convert a 1D array into a 2D column vector for proper broadcasting in operations like matrix multiplication(but here subtraction).

print(first_array[:,None])  # first_array[:, np.newaxis]  # ✅ Equivalent, does the same thing
# But Ensure dimensions match when stacking arrays

[[ 3]
 [11]
 [ 4]
 [ 5]]


## Some more facts about `np.resape`
**np.reshape** not change in the existing array

In [5]:
# We can specify -1 for exactly one dimension in the shape to let NumPy infer the dimension.
myArray = np.array([
    [1,2,3],
    [4,5,6]
])
myArray.reshape(-1,2)
# OUTPUT:
# array([[1, 2, 5],
#        [3, 4, 9]])

array([[1, 2],
       [3, 4],
       [5, 6]])

#### **order** parmater in `np.reshape` method
[See this video clip to know about order parameter](https://youtu.be/eClQWW_gbFk?si=EX0yolG3drTqUVBW&t=2931)


In [6]:
bar = np.array([
    [1,2,3],
    [4,5,6]
])

""" 'C' (C-style / Row-major order):

Default behavior.

Elements are read and written row-wise.

Traverses the last axis (innermost dimension) first, then moves outward. """

import numpy as np

arr = np.arange(6)  # [0, 1, 2, 3, 4, 5]
reshaped = np.reshape(arr, (2, 3), order='C')
print(reshaped)
# OUTPUT:
# [[0 1 2]
#  [3 4 5]]
# - Elements are filled row-wise.




[[0 1 2]
 [3 4 5]]


In [7]:
arr2 = np.arange(6)  # [0, 1, 2, 3, 4, 5]
""" 'F' (Fortran-style / Column-major order):

Elements are read and written column-wise.

Traverses the first axis (outermost dimension) first, then moves inward. """

reshaped2 = np.reshape(arr2, (2, 3), order='F')
print(reshaped2)

# OUTPUT:
# [[0 2 4]
#  [1 3 5]]


[[0 2 4]
 [1 3 5]]


In [8]:
""" 'A' (Preserve order):

Tries to preserve the original array's memory layout.

If the input array is C-contiguous, it behaves like 'C'; if F-contiguous, it behaves like 'F'. """

"""
Contiguous ? 
Explain in below cell
"""

arr3 = np.arange(6).reshape(2, 3, order='F')  # F-contiguous
reshaped3 = np.reshape(arr, (3, 2), order='A')
print(reshaped3)

# OUTPUT:
# [[0 1]
#  [2 3]
#  [4 5]]

[[0 1]
 [2 3]
 [4 5]]


#### In NumPy, contiguous refers to how elements of an array are stored in memory. It describes whether the array's elements are arranged in a continuous block of memory and in what order.

##### Key Concepts:
1. C-contiguous (Row-major):

- Elements are stored row-wise in memory.

- The last index (innermost dimension) changes the fastest.

- Example: For a 2D array, moving across rows first, then down columns.

2. F-contiguous (Column-major):

- Elements are stored column-wise in memory.

- The first index (outermost dimension) changes the fastest.

- Example: For a 2D array, moving down columns first, then across rows.

In [24]:
# Example

# C-contiguous array (default)
arr_c = np.arange(6).reshape(2, 3)  # Row-major
print('Original arr_c\n',arr_c)
print("C-contiguous:", arr_c.flags['C_CONTIGUOUS'])  # True

# F-contiguous array
arr_f = np.asfortranarray(arr_c)  # Column-major
print("F-contiguous:", arr_f.flags['F_CONTIGUOUS'])  # True

# Reshape with order='A'
reshaped_c = np.reshape(arr_c, (3, 2), order='A')  # Behaves like 'C'
reshaped_f = np.reshape(arr_f, (3, 2), order='A')  # Behaves like 'F'

print("Reshaped C-contiguous:\n", reshaped_c)
print("Reshaped F-contiguous:\n", reshaped_f)

Original arr_c
 [[0 1 2]
 [3 4 5]]
C-contiguous: True
F-contiguous: True
Reshaped C-contiguous:
 [[0 1]
 [2 3]
 [4 5]]
Reshaped F-contiguous:
 [[0 4]
 [3 2]
 [1 5]]


#### As we know np.reshape method just create copy of given array, instead of changing in existing array
##### Still if we wanna change in existing array we obviously can do this
```
bar = bar.reshape(n,n) 
```
***but it still makes uncessary copy of bar in memory***

##### So instead do this:
```bar.shape = (n,n)```

[When numpy will broadcast and when not](https://youtu.be/g9g34UIFfMg?si=MdmzAi3Gm-XyICVp&t=427)