[See this video](https://youtu.be/eClQWW_gbFk?si=lhHEswSfZrZFGjmI&t=3547)

In [81]:
import numpy as np
np.random.randint(1, 10, size=(3, 3)) # 3x3 array of random integers between 1 and 10, high is exclusive

array([[2, 6, 8],
       [3, 5, 9],
       [2, 3, 2]])

In [82]:
np.random.rand(3, 3) # 3x3 array of random floats between 0 and 1

array([[0.60306013, 0.54506801, 0.34276383],
       [0.30412079, 0.41702221, 0.68130077],
       [0.87545684, 0.51042234, 0.66931378]])

In [83]:
np.random.randn(3, 3) # 3x3 array of random floats from standard normal distribution


array([[ 1.79988945,  1.23836635,  0.91375695],
       [ 0.46626803,  0.12503966, -0.19765092],
       [-0.72803492, -0.61031342, -0.87304897]])

In [84]:
# set seed for reproducibility
# old way
np.random.seed(123)
print(np.random.randint(1, 7, size=3))

[6 3 5]


In [85]:

# numpy.random.choice() - https://youtu.be/eClQWW_gbFk?si=DW8wQdM6ckyfExCv&t=3626

my_list = [1,2,3,4,5] # can use string values as well
np.random.choice(my_list, size=10, replace=True) # or np.random.choice(5, size=10, replace=True)

array([3, 2, 4, 3, 4, 2, 2, 1, 2, 2])

In [86]:
# let's say we want three sample rows from the following array

my_array2 = np.arange(1,11).reshape(5,-1) # -1 means as many columns as needed

print('my_array2:\n',my_array2)

my_array2[np.random.randint(0,my_array2.shape[0],size=3)]



my_array2:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([[1, 2],
       [1, 2],
       [3, 4]])

In [87]:
# shuffle an array, np.permutation() for make a new copy, np.random.shuffle() for in place shuffling
# but both methods are just shuffle along the first axis, so use default_rng() for more control, for that see below markdown

my_array3 = np.arange(1,11).reshape(5,-1)

np.random.seed(42)
print('my_array3 before shuffling:\n',my_array3)

np.random.shuffle(my_array3)

np.random.seed(42)
print('my_array3 after shuffling:\n',my_array3)


my_array3_copy = np.random.permutation(my_array3)

print('my_array3_copy:\n',my_array3_copy)

my_array3 before shuffling:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
my_array3 after shuffling:
 [[ 3  4]
 [ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
my_array3_copy:
 [[ 9 10]
 [ 7  8]
 [ 5  6]
 [ 3  4]
 [ 1  2]]


[All of the above methods are deprecated, reason,and what to do now? See this clip](https://youtu.be/eClQWW_gbFk?si=u8DGnPOC0Ds7GNsY&t=3987)

[Go to : All substitutes of above methods](https://youtu.be/eClQWW_gbFk?si=J_bmxpR1qxBz_BJu&t=4177)