## https://youmtu.be/eClQWW_gbFk?si=aigCeGn7DzmzLrZo&t=1758 , see this clip by `GormAnalysis` to see basic math operations on numpy arrays
## [or see this video by `CampusX`](https://www.youtube.com/live/40xGMygHMDU?si=SK8MkJfsiLPWB4tS&t=3865)

In [2]:
# If you wanna perform matrix multiplication

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


# So now it do row and column wise multiplication , instead of element wise multiplication
print(np.matmul(a, b)) 
a@b # or simply do this


[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])

In [3]:
# numpy.argmin - https://numpy.org/doc/2.1/reference/generated/numpy.argmin.html 
# for calculation of index of minimum value in array

rng = np.random.default_rng(42)
a = rng.integers(0, 10, size=(3, 3))
print(a)

a.argmin(axis=0) # 0

[[0 7 6]
 [4 4 8]
 [0 6 2]]


array([0, 1, 2])

In [4]:
# we also have one more feature of numpy.sum we can use where as a argument in np.sum 

rng = np.random.default_rng(42)
a = rng.integers(0, 10, size=(3, 3))
print(a)

print(np.sum(a, axis=1, where=(a % 2 == 0))) # so sum of all even elements in each row 

[[0 7 6]
 [4 4 8]
 [0 6 2]]
[ 6 16  8]


In [5]:
# numpy.nan_to_num replaces NaNs (Not a Number) and infinities in an array with specified values.
# numpy.nan_to_num(x, copy=True, nan=0.0, posinf=None, neginf=None)

""" 
Parameters:
x (array-like): Input array.

copy (bool, default=True): If True, returns a copy; if False, modifies x in place.

nan (float, default=0.0): Value to replace NaNs.

posinf (float, default=None): Value to replace positive infinity (+inf). If None, uses finite max value.

neginf (float, default=None): Value to replace negative infinity (-inf). If None, uses finite min value. """


arr = np.array([1, np.nan, np.inf, -np.inf, 5])
new_arr = np.nan_to_num(arr, nan=-1, posinf=9999, neginf=-9999)



# Output:
""" [    1    -1  9999 -9999     5]
Explanation:

NaN → -1

+inf → 9999
-inf → -9999
Other values remain unchanged.
 """

print(new_arr)







[ 1.000e+00 -1.000e+00  9.999e+03 -9.999e+03  5.000e+00]


In [6]:
# numpy.nansum Explanation
# numpy.nansum computes the sum of an array while ignoring NaN values(treat them as 0s).

# Syntax:

# numpy.nansum(a, axis=None, dtype=None, out=None, keepdims=False)

# Parameters:
"""
a (array-like): Input array.
axis (int or tuple, default=None): Axis along which to sum. If None, sums all elements.
dtype (data-type, default=None): Specifies output data type.
out (ndarray, default=None): Optional array to store results.
keepdims (bool, default=False): If True, retains reduced dimensions. """

import numpy as np

output_array = out=np.zeros(3)
arr = np.array([[1, np.nan, 3], [4, 5, np.nan]])
result = np.nansum(arr, axis=0,out=output_array)

""" Output:

[ 5.  5.  3.]
Explanation:
Ignores NaN while summing.

Sum along axis=0 results in:

(1 + 4) = 5

(NaN ignored, only 5)

(3 + NaN ignored) = 3
"""
print(result)
print(output_array)




[5. 5. 3.]
[5. 5. 3.]


In [7]:
# Trignometric function 
rng = np.random.default_rng(42)
a = rng.integers(0, 10, size=(3, 3))
print(a)

print(np.sin(a)) # sin of each element in array, you can do cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, arctanh as well

[[0 7 6]
 [4 4 8]
 [0 6 2]]
[[ 0.          0.6569866  -0.2794155 ]
 [-0.7568025  -0.7568025   0.98935825]
 [ 0.         -0.2794155   0.90929743]]


In [8]:
## dot product
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b)) # dot product of two arrays, remember columns of first array should be equal to rows of second array, otherwise it will give error
print(a @ b) # or simply do this

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [20]:
# log and exp
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.log(a)) # log of each element in array, you can do log2, log10 as well, it take base `e` , euler number - 2.71828

print()
print(np.exp(a)) # means euler(2.718) raise to the power of each element of array

print()
print(np.exp2(a)) # means 2 raise to the power of each element of array

[[0.         0.69314718]
 [1.09861229 1.38629436]]

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

[[ 2.  4.]
 [ 8. 16.]]


In [10]:
# calculating exponent

import numpy as np
a = np.arange(10)

""" 🔍 What np.exp(a) does:
It applies the natural exponential function `e^x` to each element in array a. """
# So if:
# a = np.arange(10)
# a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
""" Then:
np.exp(a)
= [e^0, e^1, e^2, ..., e^9], where e is the euler number ≈ 2.71828, It’s the base of the natural logarithm """ 



np.exp(a)



array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
# If you want to compute powers of some other base, like 2^x or 10^x, use:
# np.power(base, exponent)

a = np.arange(10)
# It raises the base 2 to the power of each element in the array a.
print(np.power(2, a))

# OR element-wise:
np.power(np.array([2, 3, 4]), np.array([3, 2, 1]))  # [2^3, 3^2, 4^1] → [8, 9, 4]

[  1   2   4   8  16  32  64 128 256 512]


array([8, 9, 4])

[Calculate Sigmoid](https://www.youtube.com/live/40xGMygHMDU?si=T_WdisEEbTpLNn2V&t=4007)

```math
\frac{1}{1+e^{-x}}

```
Where:
- e is euler number - 2.71828
- x is the input array

In [12]:
def sigmoid(array):
    return 1 / (1 + np.exp(-array))
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

- Binary cross entropy already explained in another file
Formula 

```math
BCE = \frac{-1}{N} \sum_{i=1}^N (y_i \log(\hat{y}_i) + (1-y_i) \log(1-\hat{y}_i))
```

In [13]:

actual_labels = np.array([0, 1, 0, 1, 0, 1, 0])
predicted_labels = np.array([0.1, 0.9, 0.2, 0.8, 0.3, 0.7, 0.4])

# Binary Cross Entropy
def binary_cross_entropy(y_true, y_pred):
    epsilon = 1e-15  # small constant to avoid log(0), becuase log(0) is undefined
    y_true = np.array(y_true).flatten()
    y_pred = np.array(y_pred).flatten()

    if y_true.shape != y_pred.shape:
        raise ValueError("y_true and y_pred should have the same shape.")
    
    # Clip predictions to avoid log(0)
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)

    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))


# Usage
loss = binary_cross_entropy(actual_labels, predicted_labels)
print("Binary Cross Entropy Loss:", loss)

Binary Cross Entropy Loss: 0.26874052079821825
