## https://youmtu.be/eClQWW_gbFk?si=aigCeGn7DzmzLrZo&t=1758 , see this clip by `GormAnalysis` to see basic math operations on numpy arrays

In [4]:
# If you wanna perform matrix multiplication

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


# So now it do row and column wise multiplication , instead of element wise multiplication
print(np.matmul(a, b)) 
a@b # or simply do this


[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])

In [37]:
# numpy.argmin - https://numpy.org/doc/2.1/reference/generated/numpy.argmin.html 
# for calculation of index of minimum value in array

rng = np.random.default_rng(42)
a = rng.integers(0, 10, size=(3, 3))
print(a)

a.argmin(axis=0) # 0

[[0 7 6]
 [4 4 8]
 [0 6 2]]


array([0, 1, 2], dtype=int64)