# Boolean Indexing in arrays
#### So basically with the help of boolean indexing we can filter the array based on the condition

[Understand boolean indexing by this video](https://youtu.be/eClQWW_gbFk?si=wse9qp08CZziPkvq&t=3157)

In [3]:
import numpy as np
foo = np.array([ 
    [7,8,7],
    [4,3,2],
    [7,2,7]
])

print('We return True for every element, therefore we get every element of the original array\n',foo[True],'\n')

# it will return the boolean array of same shape as foo array, where it put True at the position where the condition is true
print('element is 7:\n',foo == 7,'\n')

# let's say we want to filter the array based on the condition that the value(that filtered_foo array will contain) should be greater than 5
filtered_foo = foo[foo>5] # now it return only those elements in the output array, for which condition(inside []) returns true 
print('filtered_foo array:\n',filtered_foo,'\n')

# now we can perform operation on filtered_foo array, its literally very handy in many cases

# we can also use this boolean indexing to filter the array based on multiple conditions

# can use & , | , ~ for and, or , not in arrays

# For AND condition (values between 5 and 7)
print('element is between 5 and 7:\n',(foo > 5) & (foo < 7),'\n')

# For OR condition (values less than 3 or greater than 7)
print('element small than 3 or greater than 7:\n',[(foo < 3) | (foo > 7)],'\n')

# For NOT condition (values not equal to 7)
print('Not 3:\n',[(foo != 3)]) # or print('Not 3:\n',[~(foo == 3)])


We return True for every element, therefore we get every element of the original array
 [[[7 8 7]
  [4 3 2]
  [7 2 7]]] 

element is 7:
 [[ True False  True]
 [False False False]
 [ True False  True]] 

filtered_foo array:
 [7 8 7 7 7] 

element is between 5 and 7:
 [[False False False]
 [False False False]
 [False False False]] 

element small than 3 or greater than 7:
 [array([[False,  True, False],
       [False, False,  True],
       [False,  True, False]])] 

Not 3:
 [array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])]


In [4]:
another_foo = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

row1_and_3 = [True,False,True]

print('row1_and_3:\n',another_foo[row1_and_3],'\n')

row1_and_3:
 [[1 2 3]
 [7 8 9]] 



In [5]:
# But if we do this:
           #  0      1     2      ✕      1    2
# another_foo[[True, True, True], [False, True, True]] # shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,)

## Let's break it down step by step and see what numbers NumPy tries to use, and so gives error


#### Step 1: Understanding Boolean Indexing

```
another_foo[[True, True, True], [False, True, True]]
```

We need to see how NumPy converts these boolean lists into actual indices.


#### Step 2: How NumPy Converts Boolean Arrays
Row Indexing: [True, True, True]
A boolean list for row indexing selects the rows where the value is True.
In this case, [True, True, True] means select all rows.


Equivalent numeric indices
```
[0, 1, 2]  # (Row indices)
```

Column Indexing: [False, True, True]
- You might think NumPy converts [False, True, True] to [0, 1, 1] (wrong).
- But actually, NumPy converts [False, True, True] to:

```
[1, 2]  # (Column indices) # Because its return False for 0th column and True for 1st and 2nd column
```

#### Step 3: Why This Fails
Now, NumPy tries to match the row and column indices element-wise:

```
Row Index  (shape (3,))   | 	Column Index (shape (2,))
[0, 1, 2]                 |	    [1, 2]               
```

- Rows have 3 values, but columns have only 2!
- NumPy tries to pick elements like (0, 1), (1, 2), (2, ?), but there's no third column index to match row index 2.
- Shape mismatch occurs → NumPy throws an IndexError.

####  Step 4: Correct Way to Achieve This
✅ If you want to select all rows and specific columns, use:

```
another_foo[:, [False, True, True]]  # Works, selects columns 1 & 2 for all rows
```

Output:

```
array([
    [2, 3],
    [5, 6],
    [8, 9]
])
```

✅ Works because:

: → Selects all rows ***(Not interpreted as list indexing(for rows))***<br>
[False, True, True] → Selects columns [1, 2] ***Means Select 1st and 2nd column of all rows***









In [6]:
# We can also index arrays like this 

foo = np.array([
    [3,9,7],
    [1,2,3],
    [7,7,3]
])

mask= foo ==7

# Its Same as this 
""" 
foo[[[False, False,  True],
       [False, False, False],
       [ True,  True, False]]]  """

print(foo[mask])



[7 7 7]


In [12]:
# One more Example: 
# Only wanna get age of male who are above or equal to 44

names = np.array(['a','b','x','y','u'])

ages = np.array([23,44,56,77,12])

gender = np.array(['male','female','male','female','male'])

# let's use & for this
names[(ages>=44) & (gender == 'male')]

# Who's not a male or younger than 44
names[~(ages>=44) | (gender == 'female')]

array(['a', 'b', 'y', 'u'], dtype='<U1')