Both ravel() and flatten() convert a NumPy array into a 1D array, but they behave slightly differently.


## Difference between ravel() and flatten()

| Feature            | ravel()                         | flatten()                  |
|--------------------|--------------------------------|----------------------------|
| Return Type       | Returns a view (if possible)   | Always returns a copy      |
| Memory Usage      | Efficient (modifies original if possible) | Uses extra memory |
| Modifies Original? | Yes (if it returns a view)    | No (since it returns a copy) |
| Performance       | Faster                          | Slightly slower           |


#### What's a view : A view in NumPy is an array that shares the same data as the original array but presents it in a different shape or order. Modifying a view also modifies the original array.

Note: ravel() returns a 1D view of the original array if possible (i.e., when the array is stored in a contiguous block of memory). This means that modifying elements in ravel() also modifies the original array.

However, it does not change the shape of field(original array) itself. The original field remains a 2D array, and the updates happen in place.

In [12]:
import numpy as np

field = np.zeros((10, 10))
field.ravel()[np.arange(10)] = 1
print(field.ravel())
# see not change shape of a original array `field`
print(field)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
