## Problem Statement
You're given a 10x2 array of floats where each row represents a movie. The first column represents the movie's rating and the second column represents the director's rating. Your goal is to create a third column to represent the overall rating. The overall rating is equal to the movie rating if it exists, otherwise it's the director's rating.

In [5]:
import numpy as np

generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
ratings[[1, 2, 7, 9], [0, 0, 0, 0]] = np.nan

print(ratings)

np.isnan(ratings[:, 0])

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [ 5.  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [nan  5.]]


array([False,  True,  True, False, False, False, False,  True, False,
        True])

In [ ]:
count = np.where(np.isnan(ratings[:, 0]), ratings[:, 1], ratings[:, 0]).reshape(10,1)

resultant_Array = np.hstack((ratings,count))
resultant_Array

array([[ 7.,  1.,  7.],
       [nan,  2.,  2.],
       [nan,  8.,  8.],
       [ 9.,  3.,  9.],
       [ 8.,  9.,  8.],
       [ 5.,  2.,  5.],
       [ 8.,  2.,  8.],
       [nan,  6.,  6.],
       [ 9.,  2.,  9.],
       [nan,  5.,  5.]])

## This work can also be dony by `np.insert` method , - [see here](https://youtu.be/eClQWW_gbFk?si=8JRBfKOrFLli8HQW&t=5975)