You're a vindictive, hateful professor and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide to give 0s to the first three students who score less than sixty, in the order they turned in their exams. So, given a 1D array of integers, identify the first three values less than sixty and replace them with zero.

In [1]:
import numpy as np 

generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))

print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [ ]:
allIndicesScrBelow60 = np.argwhere(scores < 60)

scores[allIndicesScrBelow60[:3]] = 0

# 
print(scores)


[68.  0. 76.  0.  0. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


array([66, 67, 57, 65, 63, 86, 80, 77, 86])